export default {
  components: {
    gangWeiLeiBie: "Job category",
    miMa: "Password",
    tiJiao: "Submit",
    bianJiZhangHao: "Edit account",
    xinJianZhangHao: "New account",
    qingShuRuDaiLi: "Enter the agent account.",
    shuRuDaiLi: "Enter affiliate",
    keJianDaiLi: "Visible affiliate",
    youXiaoShiJian: "Valid time",
    zhangHaoYouXiaoQi: "Account validity",
    qingXuanZeGangWei: "Select a job category.",
    qingShuRuMiMa: "Enter your password.",
    qingShuRuZhangHao: "Enter an account name/phone No.",
    gongXiNinBianJi: "Congratulations. Account edited.",
    gongXiNinXinZeng: "Congratulations. Account created.",
    shenFenMa: "Identity code",
    shenFenYanZhengMa: "Identity verification code",
    zhongZhiShenFenYan: "Reset identity verification code",
    qingShuRuBeiZhu: "Enter the remarks.",
    beiZhuROW: "Remarks: {val1}",
  },
  config: {
    tianJiaBeiZhu: "Add note",
    xiuGaiRen: "Modified by:",
    gangWeiMingCheng: "Job name",
    buMenMingCheng: "Department name",
    qingShuRuZhangHao: "Enter an account name/phone No.",
  },
  index: {
    yunWeiGuanLiXi: "O&M management system",
  },
};
