export default {
  components: {
    quanBuGuanBi: "Close all",
  },
  config: {
    tongBu: "Sync",
    zhuanZhangDaoHuiYuan: "Transfer to member account",
    daiLiZhuanZhang: "Agent transfer",
    xinJianXiaJiDai: "New sub agent",
    daiLiQuanXian: "Agent permissions",
    eDu: "Quota",
    shengYuXinYong: "Remaining credit",
    zhangHuYuE: "Account balance (",
    guanFangChouYong: "(Commission taken by the platform)",
    huiYuanFanYongFang: "Member rebate plan:",
    yongJinFangAnLei: "Commission plan type",
    daiLiCengJi: "Agent level",
    qingShuRuGuanJian: "Enter keywords.",
  },
  details: {
    neiBu: "Internal",
    yuJiYongJin: "Expected commission",
    huoDongHongLiXiang: "Event bonus details",
    lingQuShiJian: "Collection time",
    lingQuZhuangTai: "Collection status",
    jiangLiJiaZhi: "Bonus value",
    jiangLiLeiXing: "Reward type",
    huoDongLeiXing: "Event type",
    jiangLiFaFangShi: "Reward distribution time",
    daiLiQuanXianGuan: "Agent permission management",
    tongIPDiZhi: "Search on duplicate IP address",
    tongSheBeiHaoCha: "Search on duplicate device number",
    chaXunRiQiQu: "The query date range cannot exceed {val1} days.",
    jinGeYueDengLu: "Total logins in the last 3 months",
    zuiHouDengLuShi: "Last login time:",
    tiShiDianJiShe: "Tip: Click the device number to search for the associated member information.",
    jinGeYueDengLu2: "Total logins in the last 3 months",
    zuiHouYiCiDeng: "Last login time",
    gong: "Total",
    weiHuoQuDaoCi: "Failed to get the device number",
    sheBeiHaoDengLu: "Device number (logins/proportion)",
    sheBeiLeiXing: "Device type",
    shouJiHaoGuiShu: "Phone No. based in",
    iPGuiShuDi: "IP address based in",
    iPDiZhiDeng: "IP address (logins/proportion)",
    xiuGaiFOR: "{val1} updates under review. Please wait.",
    tiaoZhengXinYongE: "Adjust credit limit",
    iTEMS: "{val1} is required.",
    gaiZhangHaoDingJi: "The top agent for the account is",
    yiChangJiLu: "Exception log",
    houTaiCaoZuoJi: "Backend operation log",
    qianTaiCaoZuoJi: "Frontend operation log",
    zhiXing: "Run",
    piLiangCaoZuo: "Batch operation",
    shuJuGengXinShi: "Data update time: {val1}",
    erShenShiJian: "Final review time",
    yiShenShiJian: "First review time",
    shenQingYuanYin: "Reason for request",
    xiuGaiHou: "After modification",
    xiuGaiQian: "Before modification",
    caoZuoLeiXing: "Operation type",
    tiBiDiZhiT: "Withdrawal address: {val1}",
    zuiDiYouXiaoHui: "Minimum number of active members:",
    yongJinLianMoShi: "Commission chain mode",
    fenPeiBaiFenBi: "Allocation percentage:",
    jiDaiLi: "-level agent:",
    yongJinFangAn: "Commission plan",
    chouYongBaiFenBi: "Commission percentage",
    zhuangTaiCON: "Status: {val1}",
    qingSuanEDuC: "Settlement limit: {val1}",
    eDuOPT: "Limit: {val1}, status: {val2}",
    xiuGaiBeiZhuC: "Modify remarks: {val1}",
    yinHangKaID: "Bank card ID: {val1}",
    bianGengWei: "Change to:",
    xiuGaiDaiLiFan: "Modify agent rebate mode",
    zhuangTaiXiuGaiJie: "Status change: unlock",
    zhuangTaiXiuGaiJian: "State change: indirect lock",
    zhuangTaiXiuGaiWan: "State change: full lock",
    zhongZhiYinHangKa: "Reset bank cards",
    xiuGaiCON: "Modify: {val1}",
    shangJiDaiLiI: "Superior agent ID: {val1}",
    yinLianSaoMaZhi: "Payment via UnionPay code scan",
    xiTongDingDanChuang: "System - Failed to create an order",
    sanFangDingDanChuang: "Third-party - Failed to create an order",
    weiTuiJian: "Not recommended",
    yiTuiJian: "Recommended",
    buDanShenQingBei: "Additional order request remarks",
    ziJinTiaoZhengEr: "Final review remarks for fund adjustment",
    ziJinTiaoZhengYi: "First review remarks for fund adjustment",
    ziJinTiaoZhengShen: "Fund adjustment request",
    zhiFuShiBai: "Payment failed.",
    jiangXiNongCunXin: "Jiangxi Rural Credit Cooperatives",
    huBeiYinHang: "Hubei Bank",
    guiZhouShengNongCun: "Guizhou Rural Credit Cooperatives (Rural Commercial Bank)",
    fuJianShengNongCun: "Fujian Rural Credit Union",
    quanZhouYinHang: "Bank of Quanzhou",
    shaoXingYinHang: "Bank of Shaoxing",
    beiJingShangYeYin: "Beijing Commercial Bank",
    wuHanNongShangYin: "Wuhan Rural Commercial Bank",
    hengFengYinHang: "Hengfeng Bank",
    guangXiShengNongCun: "Guangxi Rural Credit Cooperative",
    guangXiBeiBuWan: "Guangxi Beibu Gulf Bank",
    jiLinYinHang: "Bank of Jilin",
    qingDaoYinHang: "Bank of Qingdao",
    shenZhenNongShangYin: "Shenzhen Rural Commercial Bank",
    dongWanYinHang: "Bank of Dongguan",
    guangDongShengNongCun: "Guangdong Rural Credit Union",
    zheShangYinHang: "Zheshang Bank",
    haErBinYinHang: "Harbin Bank",
    shangHaiYinHang: "Bank of Shanghai",
    nanJingYinHang: "Bank of Nanjing",
    jiangSuYinHang: "Bank of Jiangsu",
    hangZhouYinHang: "Bank of Hangzhou",
    changShaYinHang: "Bank of Changsha",
    guangZhouYinHang: "Bank of Guangzhou",
    beiJingYinHang: "Bank of Beijing",
    ningBoYinHang: "Bank of Ningbo",
    yiDongDuan: "Mobile end",
    xiaJia: "Delist",
    shangJia: "List",
    daiKeQuDao: "Intermediary channel",
    yingYongQuDao: "App channel",
    daEQuDao: "Large amount channel",
    puTongQuDao: "Ordinary channel",
    yiShenHe: "Reviewed",
    daECunKuan: "Large deposit",
    puTongCunKuan: "Ordinary deposit",
    caiWuXinXi: "Financial Information",
    quKuanCiShu: "Number of withdrawals",
    quKuanZongE: "Total withdrawal amount",
    cunKuanCiShu: "Number of deposits",
    cunKuanZongE: "Total deposit amount",
    pingTaiYuE: "Platform balance",
    tiaoZhengEDu: "Adjust limit",
    dongJieJinE: "Frozen amount",
    tiaoZhengHouEDu: "Updated limit",
    dangQianEDu: "Current limit",
    tiaoZhengKeTiXian: "Adjust withdrawal limit",
    zuiGaoKeZhuan: "Transfer limit:",
    yingFaFang: "Payable",
    leiJiWeiFaFang: "Total unpaid",
    fanLiBiLi: "Rebate ratio",
    zhangHaoZhuangTai: "Account status",
    shouXuFeiFangAn: "Service fee plan",
    yongJinXinXi: "Commission Information",
    zhuCeXinXi: "Registration Information",
    shangCiDengLuShi: "Last login time",
    zhuCeDuan: "Registration device",
    zhuCeDiZhi: "Registered address",
    shouHuoXinXi: "Receipt information",
    cengYongKaXinXi: "Information of previous cards",
    yinHangKaXinXi: "Bank card info",
    zhongZhiYinHangKa2: "Reset bank cards",
    diZhi: "URL",
    shouHuoRen: "Recipient",
    shanChuShiJian: "Deleted at",
    fenXingDiZhi: "Bank branch address",
    kaHao: "Card No.",
    chiKaRenXingMing: "Card holder's name",
    bangDingShiJian: "Bound at",
    bangKa: "Bind bank card",
    jiBenXinXi: "Basic information",
    gaiYongHuYiYou: "This user has unreviewed operations.",
    gongXiNiJieSuo: "Congratulations. Level unlocked.",
    gongXiNiSuoDing: "Congratulations. Level locked.",
    bianGengShangJiDai: "Superior agent updates under review. Please wait.",
    xiuGaiDaiLiLei: "Agent type updates under review. Please wait.",
    gongXiNiXiuGai: "Congratulations. User level modified.",
    qingXuanZeDaiLi: "Select the agent type.",
    daiLiLeiXing: "Agent type",
    cengJiSuoDing: "Level lock",
    qingXuanZeCengJi: "Select a level.",
    zhangHaoZhuangTai2: "Account status",
    qingShuRuYouXiang: "Enter an email address.",
    qingShuRuShouJi: "Enter your phone No.",
    shouJiHaoMa: "Phone No.:",
    chuShengRiQi: "Date of birth:",
    xingBie: "Gender",
    jieSuo: "Unlock",
    bangDingQianBaoDi: "Bind wallet address",
    qianBaoXieYi: "Wallet protocol",
    qianBaoBieMing: "Wallet alias",
    tuiGuangXinXi: "Promotion information",
    pREVZhuan: "Permission for {val1} to transfer to member account under review. Please wait.",
    pREVXiang: "Permission for {val1} to transfer to sub agent under review. Please wait.",
    pREVChuang: "Permission for {val1} to create agents under review. Please wait.",
    pREVHui: "Permission of top-up by members for {val1} under review. Please wait.",
    bianGengShouXuFei: "Service fee plan updates under reviewed. Please wait.",
    fORMA: "{val1})} day(s) ago",
    xiaJiDaiLiSan: "Sub agent (level 3)",
    xiaJiDaiLiEr: "Sub agent (level 2)",
    xiaXianHuiYuan: "Sub members",
    anQuanMiMa: "Security password",
    zhuanZhangDaoHuiYuan: "Transfer to member account",
    xiangXiaJiDaiLi: "Transfer to sub agent:",
    xinJianXiaJiDai: "New sub agent",
    huiYuanDaiChong: "Top-up by members",
    daiLiQuanXianKong: "Agent permission control",
    qingXuanZeShouXu: "Select a service fee plan.",
    xiaQi: "Next session",
    xiaYue: "Next month",
    benQi: "Current session",
    caoZuoDuan: "Operation end",
    shouKuanRen: "Payee",
    caoZuoHou: "After operation",
    caoZuoQian: "Before operation",
    caoZuoXiangMu: "Operation item",
    caoZuoRen: "Performed by",
    caoZuoIPDi: "Operation IP address",
    liuLanQiBanBen: "Browser version",
    dengLuSheBei: "Login device",
    dengLuWangZhi: "Login URL:",
    qingShuRuSheBei: "Enter the device number.",
    qingShuRuDengLu: "Enter the login URL.",
    qingShuRuIP: "Enter the IP address.",
    chaoShiWeiQueRen: "Failed to confirm receipt within the specified time js",
    daiQueRenDaoZhang: "Pending receipt confirmation js",
    qingShuRuTiXian: "Enter the withdrawal amount.",
    tian: "15–30 days",
    tian2: "7–15 days",
    taoLiChaXun: "Arbitrage query",
    bianGengJiLu: "Change history",
    jiaoYiMingXi: "Transaction details",
    tiXianJiLu: "Withdrawal record",
    chongZhiJiLu: "Top-up record",
  },
  examineCommissionPayment: {
    qingShuRuShenHe: "Enter the reviewer.",
    wuXiaoDingDanShu: "Number of invalid orders",
    youXiaoDingDanShu: "Number of valid orders",
    zuiHouXiaZhuShi: "Last bet placing time",
    youXiaoHuiYuanXiang: "Active member details",
    xiaJiHuiYuanYong: "Subordinate member commission. A green negative number indicates member profit, and a red positive number indicates company profit.",
    yongJinBiLi: "Commission percentage",
    gongSiJingShuYing: "Net company win/loss",
    leiJiShangYue: "Last month cumulative",
    chengBenZongJi: "Total cost",
    tiKuanShouXuFei: "Withdrawal service fee percentage (%)",
    cunKuanShouXuFei: "Deposit service fee percentage (%)",
    chengBenFeiYong: "Costs",
    xiangMu: "Project",
    xiaJiDaiLiYong: "Subordinate agent commission:",
    moShi: "Mode",
    zhiShuDaiLiShu: "Number of direct agents (active/total)",
    fanYongTEX: "Commission {val1}%",
    daiLiZhangHuMing: "Agent account name",
    xiaJiDaiLiYong2: "Sub agent commission",
    youXiaoXiaJiDai: "Number of active sub agents (active/total)",
    gongSiZongShuYing: "Total company win/loss",
    gongSiZongYingLi: "Total company profit",
    wanJiaDuiZhanGong: "PvP company vigorish",
    pingTaiZuoZhuangGong: "Platform dealership company win/loss",
    jieSuanZhuangTai: "Settlement status",
    shiJiHeJiFa: "Actual total payout",
    leiJiaShangYue: "Accruals from last month",
    youXiaoXiaJiDai2: "Total number of active sub affiliates",
    youXiaoHuiYuan: "Active member:",
    fanYongFangAn: "Rebate plan",
    yongJinFangAn: "Commission plan",
    qingXuanZeShenHe: "Select the review result.",
    qingXuanZeYongJin: "Select a commission plan.",
    qingXuanZeChaXun: "Select the query range.",
    iTEMU: "{val1} {val2}",
    shuLiangUNI: "Quantity: {val1}",
    daiLiXianTongJi: "Overview of agent statistics",
    jieSuanDanGaiYao: "Settlement order summary",
    yongJinJieGou: "Commission structure",
    paiFaYongJinZhan: "Percentage of payout commission",
    ciDaiLiWuYong: "No commission for this agent",
    wuShuJuZhanShi: "No data to show",
    erShenBeiZhu: "Final review remarks:",
    yiShenBeiZhu: "First review remarks:",
    shouXuFeiFangAn: "Service fee plan",
    yongJinJieSuanDan: "Commission settlement order No.",
    zhangHuZhuangTaiZan: "No account status",
    zhuDangGongSiJing: "Note: When the net company win/loss is negative (member profit), the commission percentage is 0% by default.",
    pinMingWeiNinJia: "... loading details for you",
    tEXTXiu: "{val1}ᅳFailed to modify {val2} entries",
    uSERN: "The total intermediary top-up amount of {val1} accounts cannot exceed the remaining amount.",
    tEXTU: "{val1}-{val2} entries",
    qingShuRuCU: "Enter {val1}",
    qingShuRuDaiLi: "Enter the agent account.",
  },
  index: {
    bianJiZiLiao: "Edit profile",
    tongBuChengGong: "Synced",
  },
  modal: {
    zhiHangDiZhi: "Branch address",
    bangDingYinHangKa: "Bind bank card",
    heJi: "Total:",
    fenPeiBaiFenBi: "Allocation percentage:",
    benJi: "(Current level)",
    zongYongJinBiLi: "Total commission percentage:",
    qingXuanZeHuiYuan: "Select the member rebate plan.",
    huiYuanFanYongFang: "Member rebate plan:",
    chouYongBaiFenBi: "Commission percentage",
    sheZhiYongJinLian: "Set commission chain",
    yongJinLianMoShi: "Commission chain mode",
    yongJinLianSheZhi: "Commission chain settings",
    weiFenPeiYongJin: "Percentage of unallocated commission {val1}%",
    heJiBuNengChao: "Must not be higher than {val1}%",
    qingXianShuRuZong: "Enter the total percentage first.",
    xiuGaiYongJinFang: "Commission plan updates under review. Please wait.",
    daHuaTou: "Liar's dice",
    lanFangBLU: "Blue Side：{val1}<br/>Red Side{val2}",
    huanLeDouNiu: "Happy bullfight",
    xia: "Below.",
    zhong: "2 out of 3",
    shang: "Up.",
    shiSanShui: "13 cards",
    zhuang: "Dealer",
    huang: "Yellow",
    xuan: "Black",
    di: "No.",
    tian: "15–30 days",
    baiRenNiuNiu: "Niu niu with 100 players",
    wanJiaPLA: "Player：{val1}{val2}",
    xingYunDian: "Lucky Blackjack",
    paiJiu: "Pai Gow",
    qiangZhuangPaiJiu: "Dealer pai gow",
    maJiang: "Mahjong",
    erBaGang: "Erbagang",
    pinSanZhang: "Three of a kind",
    qiangZhuangDian: "Dealer blackjack",
    deZhou: "Texas hold 'em 2+3",
    xingYunWuZhang: "Lucky 5 card stud",
    jingDianNiuNiu: "Classic niu niu",
    kanPaiQiangZhuang: "View cards to compete to be dealer",
    sanGong: "3 card brag",
    zhaJinHua: "3 card brag",
    tongBiNiuNiu: "Tongbi niu niu",
    qiangZhuangSanZhang: "Dealer three of a kind",
    qiangZhuangNiuNiu: "Dealer niu niu",
    erSi: "Two-four",
    dingSan: "One-two",
    zaWu: "Mixed five",
    zaQi: "Mixed seven",
    zaBa: "Mixed eight",
    zaJiu: "Mixed nine",
    lingLinLiu: "Big head six",
    gaoJiaoQi: "Long seven",
    hongTouShi: "Red ten",
    fuTou: "Axe",
    banDeng: "Chair",
    changSan: "Long",
    meiPai: "Plum",
    ePai: "Goose",
    renPai: "Man",
    diPai: "Earth",
    tianPai: "Heaven",
    baiBan: "White Dragon",
    tong: "9 Dots",
    tong2: "8 Dots",
    tong3: "7 Dots",
    tong4: "6 Dots",
    tong5: "5 Dots",
    tong6: "4 Dots",
    tong7: "3 Dots",
    tong8: "2 Dots",
    tong9: "1 Dot",
    fangKuai: "Square",
    meiHua: "Clubs",
    hongTao: "Hearts",
    heiTao: "Spades",
    guanJunTouZhu: "Championship Betting",
    gunQiuX: "In-Play 1 X 2",
    baoKuoJiaShiSai: "Includes overtime and penalty kicks",
    zhuSuoShuShangJi: "Note: The default superior is admin. You can set it to other agents, which can’t be changed again.",
    geShuZiZiMu: "A combination of 8-20 numbers/letters/special characters",
    bianJiDaiLi: "Edit agent",
    xinZengDaiLi: "Add agent",
    xinZengChengGong: "Added",
    fuZhiXinXi: "Copy information",
    dengLuWangZhi: "Login URL:",
    shouJiHaoMa: "Phone No.:",
    dengLuMiMa: "Login password:",
    daiLiZhangHao: "Agent account:",
    yongHuYiCunZai: "User already exists.",
    panKou: "<div>Market: {val1}</div>",
    shuangFang: "Both parties:",
    lianSai: "League tournament",
    xinZengShiChangBu: "Add marketing agent",
    xinZengSEO: "Add SEO agent",
    zhuanRuJinEBu: "Transfer amount cannot be less than 0.",
    qingShuRuZhuanRu: "Enter the transfer amount.",
    congZhongXinQianBao: "Transfer from main wallet {val1}",
    mWBuYuBu: "(Decimals not supported when transferring to mw fishing)",
    zhuanRuJinE: "Transferred-in amount",
    gaiZhangHuZhuZhang: "The main account balance of the account is 0.",
    gongXiNiCaoZuo: "Congratulations. The operation is successful.",
    shenQingXiuGaiZi: "Apply to modify profile",
    zhangHaoBianJiShen: "Account edits under review. Please wait.",
    paiChuSuoDing: "Exclude locked",
    yiGouXuanSE: "{val1} data entries checked",
    dangQianVIP: "Current VIP level",
    shiFouSuoDingCeng: "Whether to lock the level",
    qingXuanZeDengJi: "Select the level.",
    vIPDengJi: "VIP level",
    iSMUL: "{val1}",
    piLiangXiuGaiV: "VIP batch modified.",
    xiuGaiVIP: "VIP modified.",
    yiGuoLuDiaoV: "Users of locked VIP already filtered out.",
    qingShuRuShenQing: "Enter the reason for deletion. Limit to 45 characters.",
    shenQingShanChuYuan: "Reason for deletion",
    shenQingShanChuYin: "Apply to delete bank card",
    shanChuYinHangKa: "Bank card deletion under review. Please wait.",
    qingShuRuShenQing2: "Enter the reason for modification.",
    shenQingXiuGaiYuan: "Reason for modification",
    shenQingZhongZhiYin: "Apply to reset bank card",
    zhongZhiYinHangKa: "Reset bank cards",
    shuRuYongHuMing: "Enter username",
    gouXuanYongHuMing: "Check username",
    sELEC: "{val2} accounts including {val1}",
    xiaYiBu: "Next",
    yiXiaZhangHaoBu: "The following accounts do not exist: {val1}",
    yiGouXuanSE2: "{val1} data entries checked",
    qingShuRuGE: "Enter {val1}",
    jieSuoSuoDing: "Unlock/lock",
    yongHuKeYiDeng: "Users can log in, but they can’t bet, top up, withdraw, transfer, or top up for others.",
    shanChuBangDingDe: "Delete bound phone No./email",
    yongHuWuFaDeng: "Users cannot log into the platform",
    suoDingFangShi: "Lock method",
    dangQianZhuangTai: "Current status",
    ninYiChengGongFa: "You have initiated {val1} {val2} operations. Wait for review.",
    shiBaiPiLiangU: "Batch {val1} {val2} operations failed. Reason: {val3}",
    niYiChengGongFa: "You have initiated {val1} {val2} operations, of which {val3}\n{val4} operations failed because of {val5}",
    ninYiChengGongFa2: "You have initiated {val1} {val2} operations. Wait for review.",
    uSERL: "{val1} failed. Reason: {val2}",
    shenQingJieSuoYuan: "Reason for requesting unlock",
    shenQingJieSuo: "Request: Unlock",
    shenQingSuoDingYuan: "Reason for lock",
    shenQingSuoDing: "Request: Lock",
    shenQingPiLiangJie: "Batch request: Unlock",
    shenQingPiLiangSuo: "Apply for batch lock",
    bRYouFangR: "null",
    xiuGaiVIP2: "Modify VIP level",
    piLiangXiuGaiV2: "Batch Modify VIP level",
  },
};
