export default {
  constType: {
    huiYuan: "Member",
    anZhuo: "Android",
    huiYuanAPP: "Member - APP",
    erShenGeZhi: "Final review on hold",
    erShenJuJue: "Final review rejected",
    erShenTongGuo: "Final review approved",
    yiShenJuJue: "First review rejected",
    yiShenTongGuo: "First review approved",
    daiShenHe: "Pending review",
    daiLi: "Agent",
    cuoWuChongZhiKou: "Deduction for incorrect top-up (agent)",
    daiLiTiKuan: "Agent withdrawal",
    youXiBuFen: "Gaming for additional points",
    cuoWuDaiChongJia: "Add-back for incorrect intermediary top-up",
    daiChongZhangHuTiao: "Intermediary top-up account adjustment",
    huiYuanDaiChongKou: "Deduction for top-up by members",
    xiTongKouHui: "System deduction",
    cuoWuChongZhiKou2: "Deduction for incorrect top-up (member)",
    xuNiEDu: "Virtual limit",
    yongJinTiaoZheng: "Commission adjustment",
    daiChongFanLiTiao: "Intermediary top-up rebate adjustment",
    youXiBuFenB: "Gaming for additional points - BX Sports",
    zhuanZhangBuFen: "Transfer for additional points",
    tiXianShiBaiTui: "Return for failed withdrawal",
    renGongChongZhi: "Manual top-up",
    youXiBuFenL: "Gaming for additional points - LB Lottery",
    hongBao: "Red packet",
    huoDongHongLi: "Event bonus",
    jianBi: "Deduction",
    jiaBiBuJiRu: "Top-up - not included in the bonus",
    jiaBiJiRuHong: "Top-up - included in the bonus",
  },
  global: {
    yiShiBai: "Failed",
    yiChengGong: "Successful",
    xiaZaiZhong: "Downloading",
  },
  riskControl: {
    chongZhiFenCeng: "Top-up level",
    tiXianFenCeng: "Withdrawal level",
    zhuCe: "Register",
    shuZiHuoBiZhi: "Digital currency payment",
    huaXiaYinHang: "Huaxia Bank",
    youZhengYinHang: "Postal Savings Bank of China",
    zhongXinYinHang: "China CITIC Bank",
    xingYeYinHang: "Industrial Bank",
    pingAnYinHang: "Ping An Bank",
    minShengYinHang: "China Minsheng Bank",
    puFaYinHang: "Shanghai Pudong Development Bank",
    guangDaYinHang: "Everbright Bank",
    guangFaYinHang: "Guangfa Bank",
    jiaoTongYinHang: "Bank of Communications",
    nongYeYinHang: "Agricultural Bank of China",
    jianSheYinHang: "Construction Bank",
    gongShangYinHang: "Industrial and Commercial Bank of China",
    zhaoShangYinHang: "China Merchants Bank",
    yinHangKaChongZhi: "-- Step 2 for top-up via bank card -->\nimport",
    yongJinQianBaoYu: "Top-up for commission wallet balance",
    huiYuanDaiChong: "Top-up by members",
    gongSiShouXin: "Company credit",
    daiLiShouXin: "Agent credit",
    beiShouXin: "Creditee",
    shouXinZhangHu: "Credit account",
    daiChongZhangHu: "Intermediary top-up account",
    iPDiZhi: "IP address",
    jianJieSuoDingDeng: "Indirect lock & login lock",
    sheBeiHao: "Device number",
    zhiBoLiWuZeng: "Livestreaming gift giving",
    qiPaiChuangGuan: "Board game",
    dianZiChuangGuan: "E-gaming",
    caiPiaoChuangGuan: "Lottery game",
    huiYuanJiaJieFu: "Member holiday red packet",
    zhuanZhangTuiHui: "Transfer refund",
    suoYouXiaJi: "All subordinates",
    benJiDaiLi: "Agents at this level",
    gongSiShuYing: "Company win/lose",
    quKuanJinE: "Withdrawal amount",
    cunKuanJinE: "Deposit amount",
    ciDaiLiDeSuo: "During the statistical time, the transaction type of the transaction list for active associated members (risk control) of the agent is withdrawal, and the status is the total amount of Successful withdrawals.",
    yuan: "CNY",
    zongZiJinQuChu: "Total fund withdrawal (risk control)",
    ciDaiLiDeSuo2: "During the statistical time, the transaction types of the transaction list for active associated members (risk control) of the agent are rebate for top-up and deposit, and the status is the total Successful amount.",
    zongZiJinLiuRu: "Total fund inflow (risk control)",
    genSuiDangQianPing: "Follow the platform’s definition of active member and calculate the total number of active members of the subordinate",
    ren: "person(s)",
    zongYouXiaoHuiYuan: "Total active members",
    weiDangYueSuoShu: "The sum of the win/loss of players with a major customer tag for the month under the subordinate",
    suoShuDaKeHu: "Win/loss of major customers (risk control)",
    weiDangYueSuoShu2: "Active associated members (risk control) of the month, and the sum of the win/loss of players in the the last three months (current month, last month, the month before last month) above 50,000",
    suoShuDaKeHu2: "Associated major customers (risk control)",
    weiDangYueNeiSuo: "Active associated members (risk control) of the month, registration within the month, deposit as the transaction type in the user transaction list of the month, and above 1 "successful" entry",
    xinZengSuoShuHui: "New associated members (risk control)",
    genSuiDangQianPing2: "Follow the sub agent definition of the current platform",
    suoShuDaiLi: "Agent",
    weiDangYueNeiSuo2: "Active associated members (risk control) of the month, with betslip records, "settled" for the settlement status, rebate for top-up and deposit as the transaction type in the user transaction list of the month, above 3 "successful" entries",
    suoShuYouXiaoHui: "Active associated members (risk control)",
    daiZuiHouJieSuan: "Pending final settlement",
    suoYouXiaJiDai: "All sub agents",
    shenQingRen: "Applicant",
    erShenRen: "Final reviewer",
    yiShenRen: "First reviewer",
    xiTongHuiKou: "System rebate",
    zhiDingHuiYuan: "Specified member",
    yiSiXianShangYang: "Suspected online account maintenance",
    yiSiYiChangZhi: "Suspected abnormal payment behavior",
    yiSiShenFenXin: "Suspected identity mismatch",
    yiSiShouJiMao: "Suspected SMS modem pool level",
    yiSiFengXianShou: "Suspected risky phone level",
    yiSiFengXianShe: "Suspected risky device level",
    yiSiQiZhaShe: "Suspected fraudulent device level",
    yiSiQiZhaWang: "Suspected fraudulent network level",
    yiSiYingXiaoQi: "Suspected marketing fraud level",
    yiSiFengXianTou: "Suspected risky speculation level",
    yiSiXianShangDu: "Suspected online gambling level",
    yiSiSheHuangShe: "Suspected pornography and terrorism level",
    yiSiEYiZu: "Suspected malicious bogus loan level",
    yiSiEYiZhong: "Suspected malicious intermediary agency",
    yiSiZiLiaoWei: "Suspected data forgery and counterfeit level",
    yiSiZiLiaoWei2: "Suspected data forgery and packaging level",
    yiSiYangKaTao: "Suspected cash out by card maintenance level",
    yiSiEYiDai: "Suspected malicious loan level",
    yiSiJinRongHei: "Suspected illegal financial industry level",
    yiSiGongKaiXin: "Suspected public information breach of trust level",
  },
  wishWord: {
    woZongShiDaiZai: "How I miss the good old days. When childhood replays, when shall first laugh, then cry, and finally sleep with tears and a smile. I remain silent not because I am unhappy, but I want to empty my mind like a a quiet and clear morning. {val1}.",
    qingChenDaoLeNi: "In the morning, the hope blows in with the soothing breeze as you opens your eyes; joy comes in with the warm sunshine through the window; the happy bell brings you a happy greeting as you look at the screen. Are you ready? My friend, {val1}.",
    yongQingChenDeYang: "Bathe with the morning sun, breathe the fresh air, take a walk in the glittering rain, and say hello to a beautiful day. Accept these joyful words and blessing to spend every day in the gorgeous morning. My friend, {val1}.",
    zaoQiShenLanYao: "Wake up early and stretch, smile at the mirror, take a deep breath, and be ready for a good mood. Leave behind the worries and put on a smile to meet good luck. May you be happy all the time and all your wishes come true. {val1}.",
    chenGuangZhaoYaoXing: "Early to bed, early to rise for a refreshing day. A glass of milk and a piece of bread, put on a smile to embrace good luck. Happiness will come to you all the time. Dear friend, {val1}. May you have a beautiful day.",
    tianLiangLeMeiHao: "A beautiful day starts with the dawn. Get up, breathe the fresh air, and embrace the sunshine. Smile and remain happy for a whole day. {val1} , may you feel good.",
    yongYangGuangZhaoYao: "Enjoy the sunshine and the flowers. Drink delectable wine and may you smile and be lucky. My friend, {val1}.",
    zhengKaiYanJingGei: "Open your eyes. Here is my blessing for you to be healthy, lucky, and happy all the time.",
    zhengKaiMiRenDe: "Feast your eyes on the white clouds; put on a beautiful smile as the water flows; embrace a happy day and remain lucky. My friend, {val1}. May you be happy without worries.",
    zaoShangKongQiQing: "Breathe in the refreshing air for a smooth day; bathe in the sunshine for a salary rise; enjoy the afternoon breeze and stay young forever.",
    tIMEYi: "{val1}, I wish you to be happy every day, get rich overnight, have your dreams come true, hit the jackpot, and get promoted. I mean it.",
    tIMEWo: "{val1}, accept the first ray of sunshine in the morning.",
    tIMEGan: "{val1}. Thank you for being with me. May you have a nice day with me, be happy every minute, and all your dreams come true.",
    zaoShangChaoXiaMan: "When the sun rises, I wish you peace and safety; at noon, I wish you luck all day long; when the sun sets, I wish you happiness.",
    zaoChenKanJianHong: "May your life be promising as the rising sun; may you be joyful like the floating clouds; and may {val1} be happy every day.",
    tIMEZheng: "{val1}. Open your eyes. Here is my blessing for you to be healthy, lucky, and happy all the time. Hope you have a wonderful day.",
    tIMETian: "{val1}. May you have a good mood as clear as the clouds above.",
    tIMEKan: "{val1}. Watching the sun up again and again, I hope your day can be wonderful too.",
    buShiMeiTianDou: "null",
    baZuoTianDePi: "Relieve yourself from fatigue yesterday and light up your passion today. Give me your hand and accept my sincere greetings to cheer you on in the new day! {val1}!",
    qingChenWoHuXi: "The wind comes with your breath as I enjoy the fresh air in the early morning. I wonder where you are now? I hope to see you your happy face in the beautiful morning! {val1}!",
    qingQingDeWoLai: "Quietly I leave, just like quietly I came. I forgot something here. Happiness. Keep it to yourself! Hey, {val1}, my dear friend!",
    paShenMeLuTu: "I’m never afraid of a long way ahead. Every step forward comes with new sights and joys. Happiness is on the road. {val1}! Dear all!",
    meiLiDeZaoChen: "Release the stress and enjoy the cool breeze and soft sunshine in the autumn morning. Here comes happiness with warmth and joys, {val1}!",
    meiHaoDeYiTian: "A beautiful day begins and hope for every day. Try not to worry about tomorrow nor sigh for yesterday. Just to make today better. {val1} , all!",
    meiYiGeRiChu: "My greetings come with sunshine: wish you a rewarding day with fresh air and light mood, {val1}!",
    meiTianXingLaiGao: "Wake up every morning and tell yourself: make fewer excuses, be more generous and honey-tongued, keep your temper under control, move faster and more efficiently, put more smiles on your face, and use your brain wisely.",
    huaWuMeiYinWei: "Butterflies chase beautiful flowers. Happy dreams happen in lovely moonlit night. Love is so precious and I am always happy with you around. {val1}!",
    chunTianYiZheNi: "Spend time with you through romantic spring, lush summer, mature autumn, and thoughtful winter. Every moving life moment starts with you, {val1}!",
    qingChenDeDiYi: "The first ray of sunshine touches your bed with comforting warmth and the first bird call comes to your ears with happiness of the day. {val1}!",
    zhengKaiShuiYanZheng: "Open your sleepy eyes, get stressed up, and stride forward in high spirits. The fresh-faced youth are fighting for the ideal in the bright sunny day. Show your smile to embrace a new day. {val1}!",
    zhengKaiMingLiangDe: "Open your bright eyes from a night of sleep and embrace a new day with a big smile. {val1} , my friend! Wish you a good day of work and life!",
    cengJingShuDiaoDe: "As long as you want, you can win back what you lost! If you want more, start working from this morning! {val1}!",
    zaoShangXingLaiXiao: "Wake up with a smile for a happy mood; move your body to stay healthy; have a booming career and stay lucky from this morning on, {val1}!",
    qingChenDeYiGe: "Morning greeting for you to start afresh and have your wishes fulfilled. May happiness always spring up in your heart! {val1}!",
    qingChenDeFengQu: "May the tension go with the morning breeze and the sadness disappear in the morning fog. Compose a song of happiness with the morning dew and start your journey to happiness. Friend, {val1}!",
    woJiaoTaiYangMei: "I beg the sun to sprinkle the sunshine of happiness on you and the mood to give you a sweet dream every day. May you all the best!",
    shengHuoChuChuYou: "Pressure is everywhere. It makes you work hard during the day, yet deprives your sleep too. When you are busy, it motivates you, yet when there is free time, you can’t relax properly. Face the pressure and make the best of it, {val1}!",
    qingQingDeChenFeng: "As morning breeze shakes the bells of happiness, a cheerful song plays in my heart. Say "{val1}". Greetings to you!",
    qingChenShuGuangChu: "Wake up with happiness at your side, embrace a smile inside as the noon sun shines, and have a joyful day when the sun sets. Care for your friends from morning to night!",
    woDeXinYiHe: "Together with the morning sun, I bring happiness to you. Let us have a joyful day as the breeze blows, {val1}!",
    shiGuangYiJiuMei: "Time is beautiful as the flowers blossom. Sing a happy song and live a wonderful life. May you never forget the days we have. Remember to make yourself happy, my friend. {val1}.",
    shengHuoYouJinYou: "There are ups and downs, but you should never let your feeling get bad. Wish you a good day, my friends on the way!",
    tIMEYi2: "{val1}, I wish you to be happy every day, get rich overnight, have your dreams come true, hit the jackpot, and get promoted. I mean every word I say!",
    yiShuangShouBaRen: "May I shelter you from the rains with my hands; may my heart comfort you; may my greeting soothe you; may the message convey you my blessings—have a good day!",
    yeXuNiCuoGuo: "Perhaps you will meet good surprises the next stop. Stay cheerful when it becomes complex. Carry on and stay happy! {val1}!",
    xiaoShiHouXingFu: "Happiness is a thing when we are kids; it becomes a goal when grown-up; and it is at last a state of mind as maturity arrives. {val1}.",
    wuLunZuoShenMe: "No matter what you do, remember that you are doing it for yourself. That way you will have no complaints! Live for yourself today, another beautiful day! {val1}, my friend!",
    yiShengWenHouYi: "A greeting and a wish for you to always be happy inside...",
    tIMEPeng: "{val1}, my friend, I wish that smile would stay on your face, happiness would fill your heart, good luck would be by your side, success would follow you, and friendship would always be there for you.",
    yiJueXingLaiHao: "null",
    yuanYiGeWenHou: "May my greeting make you happy and my blessing bring you to a new start.",
    yiTianDiYiGe: "First greeting of the day to make you happy; first blessing for your work to go smoothly; first wish for you to always be happy and warm. {val1}!",
    zhengKaiYanJingGei2: "Open your eyes. Here is my blessing for you to be healthy, lucky, and happy all the time. Hope you have a wonderful day.",
    zouGuoYiXieLu: "Hardship is learned after walking roads, climbing mountains, and crossing rivers. Happiness is here when I greet you. {val1} , my friend!",
    woYiZhiXiangXin: "I am convinced that true love can evoke life force in one, while both would be happy for such vitality inside.",
    yiGeRenYaoHuo: "To have happiness, one should be neither too smart nor too stupid. They call this wisdom of life.",
    suoWeiLianXiWei: "To practice smiling is not about mechanically moving your faces, but changing your mindset and adjusting your mood. Learn to accept reality calmly, say let it be to yourself, face bad luck frankly, look at life positively, and always think the best of people. That way the sunlight will come in to drive away fear and darkness, and fill it.",
    jinTianHenDuanDan: "Today is short, but it is important. A beautiful today would not only turn yesterday's brilliance into tomorrow's brilliance, but also turn yesterday's failure into tomorrow's success. So stop thinking about the past or signing today... we should live like it is a new start every day! Only by going from zero and live every day to its fullest, we can embrace a brilliant tomorrow.",
    buYaoTaoBiWen: "Do not run away from the problem. Face it. Of course, it is not easy. No one would solve all the problems he encounters perfectly, not should he turn to it immediately. This is not the purpose of life. In fact, we get frustrated, sad, hurt, and down in case of setback. Face the problem and take time to learn, adapt, and solve it is why we live. This can shape a real person.",
    geRenZongShiNu: "Individuals always work to keep themselves from being overwhelmed by the group. If you try hard, you usually feel alone and even afraid sometimes. But any price paid to stay true to yourself is worth it.",
    renShengShiYiDuan: "Life is a journey. The path taken is the life you weave, and we cannot predict what is next. But we can seize the day, cherish everything we have, and put our feet on the ground for our destination. Don't make yourself regret. Life is always simple.",
    meiTianGaoSuZi: "Tell yourself every day to work hard. Even if you can't see the future nor hope, you should still believe in yourself. Learn to let it go. In many times, the more you care, the more you lose. In many cases, you only need to know what you are doing, instead of saying it out. You must be happy. If you can’t get something, let it go. Why push yourself so hard?",
    niZhiDaoShenMe: "Do you know what failure means? It is about fearing that you could not succeed. It is someone who is so afraid of death that he/she dares not to give it try.",
    renShengJiuShiYi: "Life is a trip to an unknown destination. Most of the time, we have no idea what comes next. Yet sometimes, we hurry along and forget the meaning of travel.",
    yiBaiZhongRenYou: "Fate varies from people to people. For some, it is a straight road; yet for others, it is full of twists and turns. But we don’t have to envy others. The most important thing is: we will meet sooner or later.",
    shengMingZhongYouYi: "It is fate to us to miss someone, and it is happiness to be missed by others. Some things begin before we notice. Commitment starts before we now. Love is born secretly. Yet some are parted inadvertently. So, each lives his own life and has his own lover. The love is no longer there. Even in the same small city, we will never meet again.",
    woMenYiZhiXun: "We have already what we have been looking for; we look around but only miss what we want. This is why we can't get what we want.",
    shengHuoZongYouXie: "Life is always frustrating. We just get sad sometimes. But we will grow after going through these things and get it when our heart aches. Joy is there when we go easy on fame and fortune, gains and losses. We can only have a life to the fullest when we stay calm.",
    lianAiDeJiNian: "A memorial to love is not the watch and necklace you gave me, nor sweet text messages and photos. What to remember in love is the changes you leave on me, like how rivers shapes the land.",
    xiangYaoWangJiYi: "The best way to get over a relationship is to commit to the next one. A breakup is not necessarily bad, for it may be the beginning of the next relationship. Remember to love crazily and stay strong in other times.",
    meiTianZaiKaiXin: "Spend every day in happiness. Love others and your family. Treat your friends and others with a sincere heart. Be honest to the society. Be lenient to life. Be honest to others. Stay a low profile. Don't stay lofty nor belittle others. To live in the world, one must be confident, respect and love himself, and work hard on his own. You are the best to rely on. Cherish friendship, love, and family affection. Cherish the good days. Every day spent means one less day left to live. Love others as yourself and never hurt them. Don't leave regrets to others or to yourself. One would not regret only when he stays conscientious. Life will be easy when you remain kind-hearted. Cherish life and the time we have. Cherish every moment of your life.",
    zaiNiShengMingDe: "In the first 30 years, you develop habits, and in the last 30 years, your habits define you.",
    zheGeShiDaiDe: "Few young ones could have the right plans. The smarter you are, the more desires you have, and the more restless you get. You should have peace of mind. Yet smart ones would think wild and be restless. Not even to mention those without inspiration. Most of the time, they are desire instead of ambition.",
    zheShiZuiHaoDe: "This is the best time with a respected, reverent, and faithful heart. Look up and put on a smile.",
    qingChenDaoYeWan: "From early morning to night, say {val1}. Early to bed and early to get up for a fit body, a happy day, a smooth work without any worry. Blessings surround you to stay happy all the time!",
    qingChenDeYuLu: "Reflected in crystal clear morning dews, singing cicadas, happy magpies, and talking sparrows wake you up. A greeting to you: {val1}, happy all the day.",
    qingChenJingYingDe: "In the morning, crystal dew drops bring sweetness, rising sun sends warmth; refreshing breeze puts on a smile on your face; and a message from friends gives you warm wishes. My friend, {val1}.",
    renShengDeMeiYi: "Every effort in life is like to shout in a valley. You don’t have to expect anyone to hear it, but the long echo is the best return you have. It means a new day and a new beginning! {val1}.",
    meiGeZaoChenWo: "Every morning, I'm waiting, waiting for you to open your eyes and find that I am before your eyes; every morning, I'm waiting, waiting for you to listen to a gentle {val1}. I want you to hear that every day, {val2}!",
    lianYeTianMiMei: "The sweet dreams chase away tiredness. Wake up and open the phone for sincere greetings. Sun rises every day, and my missing never sets. No matter when and where, you always have my blessing. {val1}!",
    ganLuWeiNiCa: "Dews polish your eyes, while sunshine brings warmth. May you be happy with my message in the early morning and spend a simple but happy day, {val1}.",
    qingChenDeDiYi2: "The first light of sunshine lights up your heart and the first tinkle of bell rouses hope. Receive the first greeting from me: {val1}, my friend, may you be happy every day!",
    qingXinDeKongQi: "Fresh air touches you soul as you breathe in sunshine and hugs happiness. Make a sweet cup of coffee and taste happiness. Receive the message of blessing and wish you {val1} happy all the time!",
    qingChenTaiYangSheng: "The morning sun gives you a good mood; the greeting makes you warm inside; and the message of blessing keeps you happy. {val1} , I wish you a good mood every day!",
    shengMingJiuShiYi: "Life is like embroidery. From the bottom, it is messy with threads, but when God looks from above, it is a flower. May this flower of your life blossom at all times. {val1} , my friend.",
    fangXiaNiDeCheng: "Stop from being mature, calm,or sophisticated. Be a child without pressure or worries and stay vigorous! My friend, {val1}, may you be lucky all the time!",
    fanChenSuShiNi: "No one can run away from the worries of the worldly life. Forget those who make you angry, cherish those who make you happy, and put those who make you worry free inside your heart.{val1}",
    shuiYanXingSongYing: "Welcome the dawn with drowsy eyes. Brush your teeth and wash your face gently. Sunshine makes me feel good in the refreshing air. A hot drink for sweet and warm time with family around. A new day, new expectations, and a wonderful life always with you!",
    daoYiJuTI: "Hey, {val1}. The blessings come along with the first ray of sunshine! Get up early and get ready for a new day full of hope. Be happy as a new season has started! Have a nice day!",
    taiYangRanRanSheng: "The sun rises as the breeze blows softly. Flowers stretch and magpies chirp. When you open your eyes, feast on the beauty of the world. When the alarm rings, accept my good wishes. May you {val1}!",
    dangDiYiShuYang: "The first ray of sunlight filters through the window to make the room golden. The first bird singing brings laughter and smile. The first message unlocks your phone with morning blessings. Baby, {val1}!",
    qingChenDeXiaGuang: "The morning sunshine can sweep away all your worries; the morning dew can bring you a happy mood; the morning flowers show you my blessing: may {val1} smile and be happy!",
    tianLiangLeLingXiang: "When the bell rings at dawn, you reluctantly open your eyes. Don't sleep. Get up before it is too late. When you smile happily, there comes a greeting. Birds chirp and flowers blossom. Happiness always follows you. {val1}, my friend!",
    chuangWaiYuMengMeng: "It rains outside, and dream is sweet inside. Sunlight lights up your heart and your dream. Open up your eyes and stay safe and happy on the road. Remember my blessings and say {val1} to you.",
    woYiShuQingChen: "Hold a beam of early morning light and gently place it on your face. May you wake up from the dream with hopeful eyes and a clam heart. This is my best wishes for you. {val1}, my friend!",
    qingRuoChaoYangXu: "null",
    baoLiuZaiDuoYe: "The more you keep, the more you lose; the more you give, the more you have. To give is how you can get. When you nourish others, you will be nourished, too. {val1}!",
    chenXiYiJiuMeng: "In the morning sun, {val1}, get up quickly and bathe in the sunshine for a warm day. Be blessed and stay simple and happy. Embrace hope in the morning and remember to smile for a new day of hope has come!",
    chenQiDeCaiDie: "The butterfly dances to show you my missing; the sparrow sings to show you my love; the morning sun shines warmly to show you my smiling faces; and the sweet morning dews give you my thanks. {val1}.",
    wanShangHao: "Good evening",
    xiaWuHao: "Good afternoon",
    wuAn: "Good afternoon",
    zaoAn: "Good morning",
  },
};
