export default {
  config: {
    shenHeZhuangTai: "Review status",
    shenQingBeiZhu: "Request remarks",
    tiaoZhengJinE: "Adjustment amount",
    shenHeRen: "Reviewer",
    shenHe: "Review",
    erShenZhuangTai: "Final review status",
    yiShenZhuangTai: "First review status",
    xuQiuLiuShuiJin: "Required turnover amount",
    keTiEDu: "Withdrawable amount:",
    tiaoZhengZiLeiXing: "Adjust subtype",
    tiaoZhengLeiXing: "Adjust type",
  },
  index: {
    quanBuLieBiao: "Full list",
    daiShenHeLieBiao: "Pending review list",
  },
  pageFundsAdjustApplyModal: {
    qingShuRuTiaoZheng: "Enter the reason for adjustment.",
    tiaoZhengYuanYin: "Reason for adjustment",
    qingShuRuSanFang: "Enter the third-party merchant order No.",
    qingShuRuGuanLian: "Enter the associated order No.",
    qingShuRuXuQiu: "Enter the required turnover amount.",
    qingShuRuTiXian: "Enter the withdrawal amount.",
    keTiXianEDu: "Withdrawable limit",
    danBiADJ: "Single transaction ≤ {val1}",
    qingShuRuChongZhi: "Enter the top-up amount.",
    tiXianLiuShui: "Wagering requirement",
    shiJiFaFangJin: "Actual amount distributed",
    jiangLiJinE: "Bonus amount",
    daiLiHuoDongXuan: "Select affiliate event",
    qingShuRuYongHu: "Enter the username.",
    ziJinTiaoZhengShen: "Fund adjustment request",
    qingXuanZeDaiLi: "Select the agent type.",
    zhangHaoSUC: "Fund adjustment for account {val1} requested",
    zhangHaoFAI: "Account {val1} does not support {val2}.",
    zhangHaoINV: "Account {val1} does not exist.",
  },
  pageFundsAdjustExamineModal: {
    jinBanNianJiaBi: "Top-ups in the past 6 months",
    qingXuanZeShenHe: "Select the review result.",
    shenHeJieGuo: "Review results",
    erShenBeiZhu: "Final review remarks:",
    yiShenBeiZhu: "First review remarks:",
    shenQingYuanYou: "Reason for request",
    erCiShenHe: "Final review",
    yiCiShenHe: "First review",
  },
  pageFundsAdjustment: {
    qingXuanZeCaoZuo: "Select the operation review type.",
  },
};
