export default {
  EditModal: {
    qingShuRuZhangHu: "Enter an account name.",
    yunXuDaoChuShang: "Allow export of superior affiliate accounts",
    daoChuShiJianFan: "Export time range",
    houTaiZhangHao: "Backend account",
  },
  config: {
    daoChuShangJiDai: "Export superior affiliate accounts",
    houTaiZhangHu: "Backend account",
    zhuZhangHuYuE: "Balance of main account",
    vIPZhuangTai: "VIP status",
    cengJiZhuangTai: "Level status",
    wanJiaCengJi: "Player level",
    piLiangDaiChong: "Batch intermediary top-up",
    piLiangBeiZhu: "Batch add remarks",
    qingShuRuDiSan: "Enter the third-party account name.",
    diSanFangZhangHu: "Third-party account name",
  },
  components: {
    baoCunShiBaiD: "Saving failed.{val1}",
  },
  details: {
    yaoQingRen: "Inviter",
    biaoQianLeiXing: "Tag type:",
    tianJiaRen: "Added by",
    tianJiaShiJian: "Added at",
    biaoQianMingCheng: "Tag name",
    qingXuanZeBiaoQian: "Select a tag name.",
    biaoQianGuanLi: "Tag management",
    gongXiNinShanChu: "Congratulations. The deletion is successful.",
    gongXiNinTianJia: "Congratulations. Added.",
    yongHuBeiZhu: "User note",
    yongHuZhuangTai: "User status",
    shengYuDaiChongE: "Available intermediary top-up credit:",
    vIPDengJi: "VIP level",
    shenQingLiYou: "Request reason",
    caoZuoLeiBie: "Operation category",
    tiBiDiZhiT: "Withdrawal address: {val1}",
    jinYanYuanYin: "Reason for mute",
    jinYanShiChang: "Mute duration",
    sheBeiHaoDE: "Device number ({val1}) added",
    queRenShiFouYao: "Add [",
    tianJiaKeXinShe: "Add trusted device number ({val1})",
    qingXuanZeTiaoZheng: "Select a level after adjustment.",
    qingXuanZeTiaoZheng2: "Select a level before adjustment.",
    xinZengKeXinShe: "New trusted device",
    sheBeiJiLuD: "Device record ({val1}) deleted",
    keXinSheBeiHao: "Trusted device number",
    buKeChaoGuoWei: "Limit to 22 characters.",
    shouDongTiaoZheng: "Manual adjustment",
    shouDongTiaoZhengShen: "Manual adjustment under review",
    jinBiXinXi: "Coin info",
    jinBiYuE: "Coin balance",
    pingTaiTongJi: "Platform statistics",
    huiYuanShuYing: "Member win/loss",
    pingTai: "Platform",
    yuLe: "Entertainment",
    tiYuDianJing: "Sports and esports",
    liuShuiXiangQing: "Turnover details",
    tiXianLiuShuiXin: "Withdrawal turnover info",
    liuShuiKaiShiTong: "Turnover statistics start time",
    shengYuLiuShui: "Remaining turnover",
    yiWanChengTouZhu: "Completed bet turnover",
    suoXuLiuShui: "Required turnover",
    yongHuYuE: "User balance",
    zongPaiCai: "Total payout",
    fINAN: "{val1} (ordinary {val2}, large {val3})",
    daiChongCiShu: "Intermediary top-ups",
    daiChongZongE: "Total intermediary top-up amount",
    yuEZongJi: "Total balance",
    zhuanRu: "Transfer in",
    yiJianHuiShou: "One-click recovery",
    nEWBA: "{val1} {val2}`}",
    baoJiJingYanZhi: "(Stay) EXP:",
    baoJiShiJian: "Time for staying in the current level:",
    shengJiJingYanZhi: "(Upgrade) EXP:",
    zuiJinDaDaoDang: "Most recent time to reach current level:",
    shengJiTiKuanCi: "(Upgrade) Number of withdrawals:",
    vIPShengJi: "VIP upgrade progress",
    zhongZhiYinHangKa: "Reset bank cards",
    huiYuanDuanSheZhi: "Member side settings",
    tiXianAnQuan: "Withdrawal security",
    fanShuiLingQu: "Collect rebate",
    gongXiNiJieSuo: "Congratulations. Level unlocked.",
    gongXiNiSuoDing: "Congratulations. Level locked.",
    shiFouISL: "{val1} express card transfer - withdrawal",
    gongXiNiXiuGai: "Congratulations. User level modified.",
    shouDongLingQu: "Manual collection",
    ziDongLingQu: "Auto collection",
    ziDongJieShouRen: "Auto accept all odds changes",
    buJieShouRenHe: "Do not accept odds changes",
    ziDongJieShouGeng: "Auto accept better odds",
    ouPan: "Europe",
    gangPan: "HK",
    dengJiSuoDing: "Level lock",
    qingShuRuDaiLi: "Enter the agent account.",
    taiWan: "Taiwan",
    xiangGang: "Hong Kong",
    aoMen: "Macao",
    daLu: "Chinese mainland +86",
    bianJiBiaoQian: "Edit tag",
    daoZhangJinE: "Received amount",
    chengGongJiLuShu: "Number of success records:",
    hongBaoJinE: "Red packet amount",
    liSanBeiShu: "Discrete multiplier",
    fanLiBi: "Rebate percentage (%)",
    sanFangYongHuLei: "Third-party user type",
    yinHangKaYongHu: "Bank card user type",
    yongHuShuXing: "User properties",
    hongBaoGuoQiShi: "Red packet expiration time",
    hongBaoFaFangShi: "Red packet distribution time",
    chongZhiChuangJianShi: "Top-up creation time",
    chongZhiDaoZhangJin: "Total top-up amount received:",
    faFangShiJian: "Issuance time",
    miLeHuiYuanRi: "X Sports Member's Day event",
    yinHangKaHuoDong: "Bank card campaign",
    dangQianYeHuiZong: "Summary of the current page",
    huoDongShiJian: "Event time",
    renWuNUM: "Task {val1}",
    haoYouLiuShuiFen: "Turnover split from friends",
    shouCunBeiTuiJian: "Reward for first deposit by the recommended person",
    shouCunTuiJianJiang: "Recommendation reward for first deposit",
    si: "Thursday",
    san: "Wednesday",
    er: "Tuesday",
    yi: "Monday",
    jinBiShangCheng: "Gold Coin Mall",
    shouDongFaFang: "Distribute manually",
    fuLiZhuangTai: "Benefit status",
    fuLiBianHao: "Benefit No.",
    ziHuoDong: "Sub-activity",
    huoDongMingCheng: "Event name",
    jiangPinMingCheng: "Prize name",
    fuLiLeiXing: "Benefit type",
    jiangPinBianHao: "Prize No.",
    jiuHuoDongMingCheng: "Existing activity name",
    xinHuoDongMingCheng: "New activity name",
    shouJianXiang: "Inbox",
    huiYuanShiFouYi: "Member's read status",
    qingShuRuNeiRong: "Enter the content.",
    xiFenLeiBie: "Breakdown category",
    xinJianLeiBie: "Message category",
    qingShuRuXiFen: "Enter a breakdown category.",
    qingShuRuXinJian: "Enter a message category.",
    shanChuShiBaiD: "Deletion failed. {val1}",
    queDingYaoShanChu: "Delete the service fee plan?",
    shanChuGongGao: "Delete notice",
    shangYue: "Last month",
    zhanNeiXin: "Internal message",
    jiangLiMingXi: "Reward details",
    zhuDanGuanLi: "Betslip management",
    fINAN2: "{val1} (ordinary {val2}, large {val3})",
    nEWBA2: "{val1} {val2}`}",
  },
  modal: {
    mODAL: "{val1} activity details",
    caoZuoShiBai: "Operation failed.",
    xianYouBiaoQian: "Existing tag",
    piLiangZengJiaBiao: "Batch add tags",
    caoZuoChengGong: "�, the operation is successful.",
    tiaoZhengLiYou: "Reason for adjustment",
    tiaoZhengHouJinBi: "Coins after adjustment",
    tiaoZhengJinBi: "Adjust coins",
    dangQianJinBi: "Current coins",
    tiaoZhengHuiYuanJin: "Adjust member coins",
    jinBiTiaoZhengShen: "Coin adjustment request",
    zuiDuoGeZiFu: "Up to 10 characters.",
    qingShuRuWeiShu: "Enter a 6-digit fund password.",
    ziJinMiMa: "Fund password",
    bei: "x",
    qingShuRuLiuShui: "Enter the wagering requirement.",
    liuShuiBeiShu: "Wagering requirement",
    qingShuRuDaiChong: "Enter an intermediary top-up amount.",
    bALAN: "{val1} CNY",
    shouCunFuLi: "First deposit bonus",
    fuLi: "Offers",
    gongXiNiChongZhi: "The top-up is successful",
    dATAF: "Failed to top up accounts including {val1}.",
    queDingWeiUS: "Top up for members including {val1}?'",
    queRenDaiChong: "Confirm top-up",
    cANOT: "Unable to top up accounts including {val1}. Please delete them.",
    uSERN: "The total intermediary top-up amount of {val1} accounts cannot exceed the remaining amount.",
    zhangHaoBuNengChao: "The number of accounts cannot exceed 20.",
    daiLiTiaoZhengWei: "Agent adjusted as",
    piLiangXiuGaiDai: "Batch modify agents",
    piLiangCaoZuoCheng: "Successful batch operation: {val1}",
    piLiangCaoZuoCheng2: "Successful batch operation: {val1}; failed: {val2}, reason: {val3}",
    bianGengWeiDaiLi: "Change to agent account name",
    dangQianDaiLi: "Current agent",
    qieJiDaiLiYue: "Important: Do not change player agent when the monthly agent settlement report is being generated.",
    zhuYiWanJiaBian: "Note: The change of player agent should be done carefully because it may cause data discrepancy in the daily agent win/loss statement.",
    zhongYaoTiXing: "Important reminder",
    wanJiaZhangHuMing: "Player account name: {val1}",
    zhanNeiXinXiangQing: "Internal message details",
    zhangHu: "Account:",
    qingShuRuShenQing: "Enter the reason for deletion. Limit to 45 characters.",
    shenQingShanChuQian: "Request wallet address deletion",
    kuaiJieDaoChu: "Quick export",
    congZhongXinQianBao: "Transfer from main wallet {val1}",
    yiGouXuanSE: "{val1} data entries checked",
    dangQianCengJi: "Current level",
    cengJiXiuGaiWei: "Level modified to:",
    iSMUL: "{val1}",
    dATAS: "{val1} User level modified",
    yiGouXuanSE2: "{val1} data entries checked",
    iSMUL2: "{val1}",
    sELEC: "{val2} accounts including {val1}",
    shiFouXuYaoPi: "Do you want to batch unlock the VIP level of the selected account? Unlocked accounts are subject to VIP upgrading and downgrading rules.",
    piLiangJieSuoV: "Batch unlock VIPs",
    yiXiaZhangHaoBu: "The following accounts do not exist: {val1}",
    yiGouXuanSE3: "{val1} data entries checked",
    buKeChaoGuoWei: "Limit to 22 characters.",
    qingShuRuGE: "Enter {val1}",
    qingTianRuHuiYuan: "Enter remarks for the new member account.",
    shanChuBangDingDe: "Delete bound phone No./email",
    ninYiChengGongFa: "You have initiated {val1} {val2} operations. Wait for review.",
    shiBaiPiLiangU: "Batch {val1} {val2} operations failed. Reason: {val3}",
    niYiChengGongFa: "You have initiated {val1} {val2} operations, of which {val3}\n{val4} operations failed because of {val5}",
    ninYiChengGongFa2: "You have initiated {val1} {val2} operations. Wait for review.",
    uSERL: "{val1} failed. Reason: {val2}",
    shuRuTiaoZhengLiu: "Enter adjusted turnover amount (negative minus, positive plus)",
    queDingXuYaoJiang: "Zero out the user's turnover?",
    queDingYaoQingChu: "Clear this turnover request?",
    queDingYaoHuiFu: "Restore this turnover request?",
    shuGuangKaiShiTong: "Loss statistics start time",
    yiWanChengLiuShui: "Completed turnover",
    liuShuiXuQiu: "Turnover request",
    dangQianLiuShuiXin: "Current turnover info",
    tiXianLiuShuiXiang: "Withdrawal turnover details: {val1} (Currency: {val2})",
    bianDongHouLiuShui: "Turnover after change",
    bianDongQianLiuShui: "Turnover before change",
    liuShuiJinE: "Turnover amount",
    zhangBianJinE: "Account change amount",
    bianDongLeiXing: "Change type",
    caoZuoDanHao: "Operation order No.",
    liuShuiZhangBianMing: "Turnover account change details",
    qingShuRuCaoZuo: "Enter the operation order No.",
    qingShuRuCaoZuo2: "Enter the operation order number",
    mODAL2: "{val1}`\n      }",
    xiuGaiYongHuCeng: "Modify user level",
    piLiangXiuGaiCeng: "Batch modify level",
  },
  utils: {
    touZhuJiLu: "Bet history",
    jiaoYiJiLu: "Transaction details",
    eDuXiangQing: "Quota details",
    quKuanJiLu: "Withdrawal records",
    cunKuanJiLu: "Deposit records",
    zhuCeSheBei: "Registration device",
    zhuCeYuMing: "Registration domain name",
    zuiHouDengRuI: "Last login IP",
    zuiHouDengRuRi: "Last login date",
    zhuCeRiQi: "Registration date",
    yaoQingRenID: "Inviter ID",
    shengRi: "Birthday",
  },
};
