export default {
  activity: {
    fuZhiQuanXianCheng: "Permission copied.",
    xiuGaiZhuangTaiCheng: "Status modified.",
    tianJiaGangWeiCheng: "Job added.",
  },
  authority_job: {
    kaiQi: "Enable",
    caiWuJingLi: "Financial manager",
    huYunJuHeZhi: "Huyun payment aggregation",
    guanBi: "Close",
  },
  fund_adjustment: {
    caoZuoChengGong: "�, the operation is successful.",
    tiaoZhengShenQingCheng: "Adjustment requested.",
  },
  fund_history: {
    baoCunXiuGaiCheng: "Modifications saved.",
    teShuQuDao: "Special channel",
  },
  fund_information: {
    shanChuChengGong: "Deleted",
    zhongGuoYinHang: "Bank of China",
  },
  fund_recharge: {
    daHuCeng: "Major customer level",
  },
  fund_warn: {
    sanFangZhangHuJin: "Third-party account balance",
    sanFangZhangHuJin2: "Third-party account balance:",
  },
  notices: {
    jinXingZhong: "In progress",
    guanLinTiJiaoYu: "null",
    aBCDBan: "ABCD version release",
    yiHaoShiTian: "8 days used",
    zhiPaiZhuErYu: "Assign to Er Zhu to update and release before 2017-01-09",
    xinXiAnQuanKao: "Information security test",
    maShangDaoQi: "About to expire",
    diSanFangJinJi: "Urgent third-party code change",
    weiKaiShi: "Not started",
    renWuXuYaoZai: "The task needs to start before 2017-01-12 20:00",
    renWuMingCheng: "Task name",
    zheZhongMuBanYong: "This template is used to remind you who has interacted with you and whose profile photo is placed on the left.",
    biaoTi: "Title",
    zhuPianYouHuiFu: "Pianyou Zhu replied.",
    miaoShuXinXiMiao: "Description",
    quLiLiPingLun: "Lili Qu commented.",
    neiRongBuYaoChao: "The content should not exceed 2 lines. Otherwise, the exceeded content is not displayed.",
    zuoCeTuBiaoYong: "The icon on the left is used to distinguish different types.",
    zheZhongMuBanKe: "This template can have different notification types.",
    niTuiJianDeQu: "Nini Qu recommended by you has passed the third interview.",
    niShouDaoLeFen: "You received 14 new weekly reports.",
  },
  user: {
    xiHuQuGongZhuan: "No. 77 Gongzhuan Road, Xihu District",
    hangZhouShi: "Hangzhou",
    zheJiangSheng: "Zhejiang",
    haiNaBaiChuan: "Unity in diversity",
    chuanMeiZi: "Sichuan girl",
    daChangTui: "Long leg",
    la: "Hot~",
    zhuanZhuSheJi: "Focusing on design",
    henYouXiangFaDe: "Creative",
    maYiJinFuMou: "Ant Group - xxx business group - xxx platform department - xxx IT department - UED",
    jiaoHuZhuanJia: "User experience expert",
    haiNaBaiChuanYou: "Unity in diversity",
  },
};
