export default {
  addNoticeLetter: {
    yuLanAPP: "Preview app effect",
    yuLanPCXiao: "Preview PC effect",
    miaoShu: "Description:",
    qingShuRuBiaoTi: "Enter a subject.",
    xuanZe: "Select",
    duoGeYongHuMing: "Separate names with commas.",
    faSongZhangHao: "Sender account",
    qingXuanZeHuiYuan: "Select the member rebate plan.",
    huiYuanCengJi: "Member level",
    faSongShiJian: "Sent at",
    faSongZhanNeiXin: "Send internal message",
    geNBSP: ", &nbsp;&nbsp;",
    nBSPN: ",&nbsp;&nbsp;fail",
    chengGongFaSong: "Sent",
    dianJiZhangHaoZhang: "(Click the account name to copy)",
    gongXiNiXiuGai: "Congratulations. User level modified.",
  },
  addUserModal: {
    tiao: "Entries",
    huiYuanLieBiao: "Member list (",
    qingShuRuSuoShu: "Enter the affiliated agent.",
    qingXuanZeVI: "Select VIP level.",
    vIPDengJi: "VIP level",
    xuanZeHuiYuan: "Select member",
    tianJia: "Add",
    qingChaXunHuiYuan: "Query the member account.",
  },
  checkAccountList: {
    xiangQing: "Details",
  },
  checkNoticeLetter: {
    huiFuNeiRong: "Reply content",
    huiFuShiJian: "Reply time",
    leiBie: "Category:",
    zhengWen: "Body",
    faSongHuiYuan: "Send members",
  },
  checkReplyLetter: {
    huiFu: "Reply",
    jieShouShiJian: "Receipt time",
    miaoShuTuPian: "Description image",
  },
  mobilePreview: {
    wuYuLanNeiRong: "No preview content for display",
    qinAiDeYongHu: "Dear users,",
  },
  replyLetterComponent: {
    buKeChaoGuoGe: "Limit to 150 characters.",
    dingShiFaSong: "Schedule send",
    liJiFaSong: "Send now",
    faSongZhi: "Send to",
    baoCunShiBaiD: "Saving failed.{val1}",
    qingXuanZeRiQi: "Select a date.",
    qingShuRuNeiRong: "Enter the content.",
  },
  typeSettingModal: {
    changDuZaiDaoGe: "It can contain 4 to 16 characters.",
    qingShuRuLeiBie: "Enter the category name.",
    leiBieMiaoShu: "Category description",
    qingShuRuLeiBie2: "Enter the category name.",
    leiBieMing: "Category name",
  },
};
