export default {
  acccountType: {
    jianJieSuoDing: "Indirect lock",
    wanQuanSuoDing: "Complete lock",
    zhengChang: "Normal",
    xinChuangJian: "Newly created",
  },
  activityManager: {
    faFangZhong: "Sending",
    yiLingQu: "Claimed",
    juJue: "Reject",
    yiFaFang: "Distributed",
    daiFaFang: "To be sent",
    xuNiTiYu: "Virtual sports",
    xiaoJinZhenRen: "188bet",
    shuangYingCaiPiao: "Win-win lottery",
    quanBingMuXuanKu: "Full screen (cool)",
    puTong: "Ordinary",
    pingYong: "Ordinary",
    erShenBuTongGuo: "Final review rejected",
    erShenWeiShenHe: "Pending final review",
    yiShenBuTongGuo: "First review rejected",
    chuShenTongGuo: "Initial review passed",
    weiShenHe: "Not reviewed",
    yiGuoQi: "Expired",
    daiLingQu: "Pending",
    yiJuJue: "Rejected",
    yiFaHuo: "Shipped",
    weiLingQu: "Not claimed",
    buKeLingQu: "Not available",
    yiShiYong: "Used",
    weiShiYong: "Unused",
    faFangShiBai: "Sending failed.",
    faFangChengGong: "Sent",
    yiLingQuDaiFa: "Collected (to be shipped)",
    keLingQu: "Claim",
    yiDaBiaoWeiLing: "Eligible but not collected",
    vIPJingYan: "VIP EXP multiplier",
    liuShuiQuan: "Turnover voucher",
    xianJinQuan: "Cash voucher",
    cunSongQuan: "Coupon for deposit",
    shiWu: "Physical object",
    laoHuJiJiuJi: "Slot relief event",
    shouCunHuoDong: "First deposit",
    tiYuChuangGuanHuo: "Sports game event",
    zhenRenChuangGuanHuo: "Live game event",
    fanShuiHuoDong: "Rebate",
    xingYunDaZhuanPan: "Lucky spin event",
    yinHangKaChongZhi: "-- Step 2 for top-up via bank card -->\nimport",
    yinHangKaZhuanZhang: "Bank card transfer",
    xuNiBiZhiFu: "Cryptocurrency payment",
    quanBuQuDao: "All channels",
    leiJiChongZhi: "Cumulative top-up",
    danCiChongZhi: "Single top-up",
    xuYao: "Required",
    buXuYao: "Not required",
    jinBi: "coins",
    vIPChengZhang: "VIP EXP",
    xianJin: "Cash",
    fou: "No",
    shi: "Yes",
    vIPDengJi: "VIP level",
    fuYingLi: "Loss",
    youXiaoTouZhu: "Valid bet",
    shangZhouLiuShuiZong: "Last week's total turnover",
    shangZhouChongZhiZong: "Last week's total top-up",
    wuEWaiQuanZhong: "No extra weight",
    puTongChouJiang: "Ordinary lucky draw",
    songLi: "Gift",
    guanKan: "Watch",
    dangRiDanCiChong: "Single top-up on the day",
    dangRiLeiJiChong: "Cumulative top-up on the day",
    renYiTouZhuQuan: "Any bet (all platforms)",
    youXiaoTouZhuQuan: "Valid bets (all platforms)",
    huoYueDengLu: "Active login",
    aPPDengLu: "Login in app",
    pCDuanDengLu: "Login on PC",
    hDuanDengLu: "Login at the H5 end",
    renYiDuanDengLu: "Login at any end",
    shaiDan: "Share order",
    faYan: "Comment",
    yuLeDuanDengLu: "Login at the entertainment end",
    tiYuDuanDengLu: "Login at the Sports end",
    hDuanDengLu2: "Login from H5 page",
    renYiDuanDengLu2: "Login from any platform",
    zhiBo: "Live stream",
    chongZhi: "Top-up",
    dengLu: "Log in",
    huoYueDengLu2: "Active login",
    aPPDengLu2: "Login in app",
    touZhu: "Bet",
    dianJingPingTai: "Esports platform",
    tiYuPingTai: "Sports platform",
    zhuBo: "Host",
    dengLu2: "Login",
    xiaoYuDengYu: "Less than or equal to",
    daYuDengYu: "Greater than or equal to",
    leiJiYingLi: "Cumulative profits",
    leiJiTouZhu: "Cumulative bets",
    cunKuanShuaiJianWan: "Players whose deposits decrease",
    touZhuShuaiJianWan: "Players whose bets decrease",
    shangTouWanJia: "Addictive players",
    banLiuShiWanJia: "Players who barely play",
    chongZhiJinE: "Top-up amount",
    huoYueTianShu: "Active days",
    zhouQiNeiBuXian: "Unlimited within the period",
    meiRiYiCi: "Once a day",
    leiJiZhengYingLi: "Cumulative positive profits",
    leiJiYouXiaoTou: "Total valid bets ≥",
    benYue: "This month",
    benZhou: "This week",
    jinTian: "Today",
    shangZhou: "Last week",
    zuoTian: "Yesterday",
    fanShuiMoBanDan: "Rebate template (single)",
    chongZhiSongLiMo: "Top-up & gift template",
    miLeHuiYuanRi: "X Sports Member's Day event",
    miLeHuiYuanRi2: "Mile Members' Day template (single)",
    yeMianXianShiMo: "Page display template",
    jieQingHuoDongMo: "Festival celebration template",
    xinRenHuoDongMo: "Newcomer event template",
    chouJiangHuoDongMo: "Lucky draw event template",
    shouCunMuBan: "First deposit template",
    tongYongBaiFenBi: "General percentage event template",
    tongYongHuoDongMo: "General event template",
    vIPChongZhi: "VIP top-up template",
    saiShiMuBan: "Match template",
    jingCaiChouJiangMo: "Quiz draw template",
    paiMingJiangLiMo: "Ranking rewards template",
    qiTaYouHui: "Other offers",
    fanShuiYouHui: "Rebate offers",
    dianZiYouHui: "E-game offers",
    caiPiaoYouHui: "Lottery offers",
    tiYuYouHui: "Sports game offers",
    zhenRenYouHui: "Live game offers",
    hDuan: "H5 end",
    yuLeDuan: "Entertainment end",
    tiYuDuan: "Sports end",
    pCDuan: "PC end",
    xianShiKaiFang: "Available for limited time",
    zanBuKaiFang: "Unavailable for now",
    wuXianQiKaiFang: "Available for unlimited time",
    jinYong: "Disable",
  },
  agentList: {
    guanFangMoShiFen: "Platform mode (share)",
    xinYongMoShiFen: "Credit mode (share)",
    guanFangMoShiChou: "Platform mode (commission)",
    shanChuUSD: "Delete USDT withdrawal address",
    shenQingRenGongBang: "Request manual binding",
    daiLiZhuanZhangDao: "Agent transfer to member account",
    xiangShangJiDaiLi: "Transfer to superior agent",
    xiangXiaJiDaiLi: "Transfer to sub agent:",
    sheZhiDaiLiXin: "Set agent's credit limit",
    sheZhiDaiLiKe: "Set agent's withdrawable limit",
    xiuGaiDaiLiZhuan: "Modify agent's transfer settings",
    xiuGaiDaiLiYong: "Modify agent's commission chain rules",
    xiuGaiDaiLiShou: "Modify agent's service fee rules",
    xiuGaiHuiYuanDai: "Modify the permission of top-up by members",
    xiuGaiDaiLiShou2: "Modify agent credit permission",
    daiChongQingSuanRen: "Intermediary top-up settlement - Manual operation settlement",
    daiChongQingSuanYin: "Intermediary top-up settlement - Bank card top-up settlement",
    xiuGaiDaiLiChuang: "Modify the agent's permission to create subordinate agents",
    shouXinYuDaiChong: "Changes to credit and intermediary top-up settings",
    daiChongFanLiFang: "Changes to rebate plan for intermediary top-up",
    shouDongCengJiBian: "Manual level change",
    daiLiLeiXingBian: "Agent type change",
    daiChongQingSuanZhang: "Intermediary top-up settlement - Account balance settlement",
    xiuGaiShangFenShe: "Modify top-up settings",
    shanChuYinHangKa: "Bank card deletion under review. Please wait.",
    jieChuSuoDing: "Unlock",
    dengLuSuoDing: "Login lock",
    zhongZhiYinHangXin: "Reset bank information",
    bianGengLianXiFang: "Change contact information",
    bianGengShangJiDai: "Superior agent updates under review. Please wait.",
    tiXianEDuTiao: "Change withdrawable amount",
    xiuGaiXiangXiaJi: "Modify the settings of transferring to subordinate agents",
    sheZhiXinYongE: "Set credit limit",
    neiBuDaiLi: "Internal agent",
    waiBuDaiLi: "External agents",
    xiuGaiDaiLiAn: "Modify agent's security password.",
    xiuGaiDaiLiZi: "Change agent's fund password.",
    chuangJianXiaJiDai: "Create subordinate agent",
    jieBangYinHangKa: "Failed to unbind the bank card.",
    bangDingYinHangKa: "Bind bank card",
    youXiangZhaoHuiDeng: "Retrieve via email - Login password",
    shouJiZhaoHuiDeng: "Retrieve via phone - Login password",
    bangDingShouJi: "Bind phone No.",
    bianJiXingBie: "Edit gender",
    bianJiShengRi: "Edit birthday",
    yueJieSuan: "Monthly settlement",
    banYueJieSuan: "Semi-monthly settlement",
    zhouJieSuan: "Weekly settlement",
    zhengZaiJieSuan: "Settling",
    weiDaBiao: "Requirement not met",
    shiBai: "Failed",
    chengGong: "Successful",
    chuLiZhong: "Processing",
    cuoWuDaiChongKou: "Deduction for incorrect intermediary top-up",
    yongJin: "Commission",
    tiXianTuiHui: "Withdrawal returned",
    daiChongFanLi: "Intermediary top-up rebate",
    jiaBiBuJiHong: "Top-up (excluded from bonus)",
    tiKuan: "Withdrawal",
    cunKuan: "Deposit",
    xiaJiSuoDing: "Subordinate lock",
    benJiSuoDing: "Current level lock",
    beiZhu: "Remark",
    xiaJiDaiLi: "Subordinate agent",
    shouJiHao: "Mobile number",
    yinHangKa: "Bank card:",
    daiLiZhangHao: "Agent account:",
  },
  auditManagement: {
    daoZhangShiJian: "Receipt time",
    shenQingShiJian: "Request time",
    guanLianDingDanHao: "Associated order No.",
    ziJinTiaoZhengDan: "Fund adjustment order No.",
    huiYuanXianXiaTi: "Member offline withdrawal",
    youXiBuFenB: "Gaming for additional points - BX Sports",
    youXiBuFenM: "Gaming for additional points - X Sports",
    youXiBuFenV: "Gaming for additional points - VR Lottery",
    youXiBuFenMi: "Gaming for additional points - X Sports Lottery",
    daiLiHuoDong: "Agent event",
    shenHeJuJue: "Rejected",
    shenHeTongGuo: "Approved",
    tongGuo: "Passed",
  },
  data: {
    qiPai: "Table games",
    dianJing: "Esports",
    buYu: "Fishing",
    laoHuJi: "Slot",
    tiYu: "null",
    zhenRen: "Live casino",
    caiPiao: "Lottery",
    vIPMeiYue: "VIP1 monthly red packet configuration does not take effect.",
    vIPShengRi: "VIP birthday reward",
    vIPShengJi: "VIP upgrade progress",
    xiaZhuShiJian: "Bet placing time",
    chongZhiShiJian: "Top-up time",
    dengLuShiJian: "Login time",
    weiZhi: "Unknown",
    jiSuZhiFuBao: "Express Alipay payment",
    jiSuWeiXinZhi: "Express WeChat payment",
    weiXinZhuanZhang: "WeChat transfer",
    zhiFuBaoZhuanZhang: "Alipay transfer",
    yinHangKaZhuanZhang: "Bank card transfer",
    cCWeiXin: "C2C WeChat",
    cCZhiFuBao: "C2C Alipay",
    cCYinHangKa: "C2C bank card",
    kuaiJieQianBao: "Quick wallet",
    yunShanFu: "UnionPay",
    qQZhiFu: "QQ payment",
    jingDongZhiFu: "JD Pay",
    yinLianSaoMa: "Scan code with UnionPay",
    kuaiJieZhiFu: "Express payment",
    weiXinZhiFu: "WeChat Pay",
    zhiFuBaoZhiFu: "Alipay",
    wangYinZhiFu: "E-bank payment",
    fanShuiJinE: "Rebate amount",
    youHuiJinE: "Discount amount",
    gongSiYingKui: "Company profit and loss",
    xiaZhuJinE: "Bet amount:",
    tiXianJinE: "Withdrawal amount:",
    shouCunJinE: "First deposit amount",
    zuiJinSanShiTian: "Last 30 days",
    zuiJinQiTian: "Last 7 days",
    daiLiDaiChong: "Top-up by agent",
    huiYuanShouCun: "First deposit by member",
    quanBuShuJu: "All data",
    xuNiShuJu: "Virtual data",
    zhenShiShuJu: "Real data",
  },
  deviantWithdraw: {
    wuCaoZuo: "No operation",
    shenHeZhong: "Under review",
    yiShanChu: "Deleted",
    shiYongZhong: "In use",
    xiTongCheXiao: "Canceled by system",
    zhuDongCheDan: "Canceled by user",
    xiTongCheDan: "Canceled by system",
    weiZhongJiang: "Not won",
    yiZhongJiang: "Won",
    weiKaiJiang: "Not drawn",
    wuXiaoDingDan: "Invalid order",
    yiQuXiao: "Canceled",
    yiJieSuan: "Settled",
    weiJieSuan: "Unsettled",
    cuoWuShangFenKou: "Deduction for incorrect top-up",
    shangFenCaoZuo: "Top-up operation",
    fanShui: "Rebate",
    yingChaoHuoDong: "EPL events",
    vIPJiangLi: "VIP rewards - Monthly VIP red packet",
    vIPJiangLi2: "VIP rewards - Birthday bonus",
    vIPJiangLi3: "VIP rewards - Upgrade bonus",
    duanWuJieHuoDong: "Dragon Boat Festival events",
    chunJieHuoDongHong: "Spring Festival events - Red packet rain bonus",
    chunJieHuoDongTi: "Spring Festival events - Bonus for sports top-up",
    chunJieHuoDongZa: "Spring Festival events - Bonus for smashing golden eggs",
    zhenRenChuangGuanHong: "Bonus for live games",
    laoHuJiJiuYuan: "Bonus for slot machine insurance",
    tiYuChuangGuanHong: "Bonus for sports games",
    zhenRenLianYingHong: "Bonus for consecutive wins of live games",
    shouChongHongLi: "Bonus for first top-up",
    hongLiBaoKuoJia: "Bonus (including top-up - included in bonus)",
    zhuanZhang: "Transfer",
    tiXianDongJieJin: "Frozen withdrawal amount",
    zhongXinQianBao: "Main wallet",
    fengXianChuLiRen: "Risk handler",
    tiXianDanHao: "Withdrawal order No.",
    xingMing: "Name:",
    zhangHaoMing: "Account name",
    zhuanZhangYiChangJian: "Transfer exception monitoring",
    daETiXian: "Large cash withdrawal",
    fuShuQianBao: "Negative wallet",
    tiXianSheBeiChong: "Withdrawal device conflict",
    tiXianIPChong: "Withdrawal IP conflict",
    riLeiJiJinE: "The 7-day cumulative amount is too large.",
    liRunYiChang: "Abnormal profit",
    pinFanTiXian: "Frequent withdrawals",
    dangRiJinEGuo: "The amount of the day is too large.",
    danBiJinEGuo: "The single amount is too large.",
    shouTiJinEGuo: "The first withdrawal amount is too large.",
    fengXianShenHeGe: "Risk review suspended",
    fengXianShenHeTong: "Risk review approved (pending payout)",
    fengXianShenHeJu: "Risk review rejected",
    fengXianDaiShenHe: "Pending risk review",
    laoHuiYuan: "Existing members",
    xinHuiYuan: "New members",
  },
  financialManagement: {
    chuKuanZhuanYuanChu: "Payout specialist processing",
    sanFangZiDongChu: "Third-party auto payout",
    juJueQiangZhiCheng: "Enforcement denied",
    tongGuoQiangZhiCheng: "Forced successfully.",
    ziDongChuKuanShi: "Auto payout failed.",
    shenQingQiangZhiCheng: "Successful enforcement request",
    juJueTuiHui: "Reject return",
    tuiHuiChengGong: "Returned",
    shenQingTuiHuiZhong: "Requesting return",
    juJueChuKuan: "Payout rejected",
    chuKuanChengGong: "Payout successful",
    geZhi: "Suspend",
    jiSuZhuanKa: "Express card transfer",
    daiLiTiXian: "Agent withdrawal",
    puTongTiXian: "Ordinary withdrawal",
    chuKuanShiJian: "Payout time",
    tiXianShiJian: "Withdrawal time:",
    daEChongZhi: "Large amount top-up",
    puTongChongZhi: "Ordinary top-up",
    zhiFuChengGong: "Paid",
    daiZhiFu: "Pending payment",
    yunShanFuZhuanZhang: "UnionPay transfer",
    daiKeChongZhi: "Intermediary top-up",
    juJueChuKuanChu: "Payout rejected (payout failed)",
    fengXianShenHeTong: "Risk review approved (pending payout)",
    yiChuLi: "Processed",
    daiChuLi: "To be handled",
    sanFangShouDongChu: "Third-party manual payout",
    ziDongChuKuan: "Auto payout",
    renGongChuKuan: "Manual payout",
  },
  maintenance: {
    qiYong: "Enable",
    quanLiangYongHu: "All users",
    zhiDingYongHu: "Specified users",
    daiLiAPP: "Agent APP (IOS/ANDROID/H5)",
    huiYuanAPP: "Member - APP",
    quDaoBao: "Channel package",
    guanWangBao: "Official website package",
    danBiTouZhu: "Single bet",
    chaiDanTouZhu: "Split bet",
    tiXian: "Withdrawal",
    chongZhiShiBai: "Top-up failed.",
    chongZhiChengGong: "Top-up successful",
    zhiXingWanBi: "Executed",
    zhengChangYunXing: "Normal operation",
    zanTing: "Timeout",
    guanWangYuMing: "Official website domain name",
    daiLiZhuanShuYu: "Agent exclusive domain name",
    gengXin: "Update",
    quanBuYongHu: "All users",
    tianJiaYongHuZu: "Add user group",
    aPPXiaZai: "App download agent domain name",
    pXDDYu: "PXDD domain name configuration",
    tiYuSSA: "Sports ssapi domain name",
    aPPKeFu: "App customer service secondary line IP",
    aPPKeFu2: "App customer service main line IP",
    keFuCiXianLu: "Customer service secondary line IP",
    keFuZhuXianLu: "Customer service main line IP",
    daiLiYuMing: "Agent domain name",
    ziXunYuMing: "Information domain name",
    lIVEC: "Livechat customer service system IP",
    zhiChiKeFuXi: "Sobot customer service system IP",
    huoQuSaiGuoYu: "Result getting domain name",
    liaoTianShiJuBao: "Chat room report domain name",
    liaoTianShiYuMing: "Chat room domain name",
    qiuDuiTuBiaoYu: "Team icon domain name",
    tiYuHYuMing: "Sports H5 domain name",
    pUSHYu: "Push domain name",
    aPPXiaZai2: "App download domain name",
    shouJiYuMing: "Phone domain name",
    pCYuMing: "PC domain name",
    sTKeFuS: "ST customer service SDK",
    sTKeFu: "ST customer service",
    lIVEC2: "Livechat customer service",
    zhiChiKeFu: "Sobot customer service",
    zhiChiKeFuXi2: "Sobot customer service system",
    lIVEC3: "Livechat customer service system",
    jiuXu: "Ready",
    daiJiaZai: "To be loaded",
    yuanShengLeiXing: "Native type",
    jianDanLeiXing: "Simple type",
    buTongGuo: "Rejected",
    anShiJianFanWei: "Delete by time frame",
    anDanHaoShan: "Delete by order No.",
    zhiXingZhong: "Executing",
    zhiXingShiBai: "Execution failed",
    zhiXingChengGong: "Executed",
    daiZhiXing: "To be executed",
    yiChang: "Error",
    dTDianZi: "DT Electronics",
    iMTiYu: "IM Sports",
    bGZhenRen: "BG Live Game",
    bTTiYu: "BT Sports",
    bBCaiPiao: "BB Lottery",
    fanYaDianJing: "AVIA Gaming",
    mWBuYu: "MW Fishing",
    iMDianJing: "IM E-Gaming",
    pPDianZi: "PP Electronics",
    beiBoQiPai: "Beibo Card Game",
    huanLeQiPai: "Happy Card Game",
    lBCaiPiao: "LB Lottery",
    bBTiYu: "BX Sports",
    pTDianZi: "PT Electronics",
    eBETZhen: "eBET Live Game",
    aGYouXi: "AG Game",
    youXiYuEDa: "Users whose game balance is greater than 0",
    iMDianJingSai: "IM E-Gaming match settlement",
    liuHeCai: "Mark six",
    feiLiuHeCai: "Non-mark six",
    paiCaiShiJian: "Payout time",
    touZhuShiJian: "Betting time",
    buFen: "Part",
    linShi: "Temporary",
    yongJiu: "Permanent",
    suoDing: "Lock",
    xiuGaiShiJian: "Modification time",
    xinJianShiJian: "Creation time",
  },
  memberList: {
    kouJian: "Deduction",
    jiangLi: "Bonus",
    qingLing: "Clear",
    shouDong: "Manual",
    ziDong: "Auto",
    erShenWeiTongGuo: "Final review not passed",
    yiShenWeiTongGuo: "First review failed",
    daiLiXingMing: "Agent name",
    shouGongTiaoZheng: "Manual adjustment",
    xiTongZiDong: "Automatic",
    yiShiXiao: "Expired",
    tiXianTuiHuiShi: "Withdrawal return failed.",
    tiXianShiBai: "Withdrawal failed",
    jiaBi: "Top-up",
    shangJiZhuanRuDai: "Transfer from superior (intermediary top-up)",
    hongLi: "Bonus",
    zhuanZhangShiBai: "Transfer failed.",
    tiXianChengGong: "Withdrawal successful",
    xiTongXiaoXiSuo: "System message (locked)",
    xiTongXiaoXiZi: "System message (funds)",
    huiFuXinJian: "Reply letter",
    huoDongXinJian: "Activity letter",
    puTongXinJian: "Ordinary letter",
    yiFaSong: "Sent",
    daiFaSong: "To be sent",
    yiDu: "Read",
    weiDu: "Unread",
    yiHuiFu: "Replied",
    daiHuiFu: "To be replied",
    weiChuLi: "Not processed",
    cengJiBianGeng: "Level change",
    xiuGaiPeiZhiXia: "Modify subordinate top-up settings",
    qingKongDangQianLiu: "Clear the current turnover limit",
    qingSuanShangFenE: "Settle top-up limit",
    xiuGaiBeiZhu: "Modify remarks",
    xiuGaiDaiLiFan: "Modify agent rebate mode",
    zhongZhiYinHangKa: "Reset bank cards",
    bianGengShouJiHao: "Change phone No. or email",
    xinZengUSD: "Add USDT withdrawal address",
    zhuanJiaGuanZhuQu: "Follow/unfollow expert",
    shanChuShouHuoDi: "Delete shipping address",
    bianJiShouHuoDi: "Edit shipping address",
    xinJianShouHuoDi: "Create shipping address",
    fanShuiSheZhi: "Rebate settings",
    touZhuSheZhi: "Betting settings",
    panKouSheZhi: "Market settings",
    tiXianDuanXinYan: "Withdrawal SMS verification",
    bangDingYouXiang: "Bind email",
    chaoShiWeiLingQu: "Expired",
    yiFaHuoLieBiao: "Shipment list",
    daiLingQuLieBiao: "To-be-collected list",
    daiFaHuoYiLing: "To-be-shipped/-collected list",
    yinHangKaChongZhi: "-- Step 2 for top-up via bank card -->\nimport",
    fuLiChunJieHong: "Spring Festival red packet",
    huiYuanJiaJieFu: "Member holiday red packet",
    bBZhouNianQing: "BB anniversary celebration",
    nBAHuoDong: "NBA events",
    aoDaLiYaJia: "Australian A-League tournament",
    zhongQiuJieHuoDong: "Mid-Autumn Festival events",
    meiZhouBeiHuoDong: "Copa America events",
    chunJieHuoDongTi: "Spring Festival events - Bonus for sports top-up",
    chunJieHuoDongHong: "Spring Festival events - Red packet rain bonus",
    chunJieHuoDongZa: "Spring Festival events - Bonus for smashing golden eggs",
    laoHuJiJiuYuan: "Bonus for slot machine insurance",
    zhenRenLianYingHuo: "Consecutive wins of live games",
    fanShuiLiJin: "Rebate bonus",
    nengLiangDian: "Energy points",
    mianFeiCaiJin: "Free bonus",
    kuiSunBuTieQuan: "Loss subsidy coupon",
    zhongJiangFanLiQuan: "Prize-winning rebate voucher",
    touZhuFanLiQuan: "Bet rebate voucher",
    chongZhiFanLiQuan: "Top-up rebate voucher (effective once)",
    shiWuJiangLi: "Physical rewards",
    vIPYueDu: "VIP monthly reward",
    vIPShengJi: "VIP upgrade progress",
    vIPShengRi: "VIP birthday reward",
    zhangBianShiJian: "Account change time",
    caoZuoShiJian: "Operation time",
    daiFuKuanJiSu: "Pending payment (express card transfer)",
    daiQueRenDaoZhang: "Pending receipt confirmation js",
    buFenTuiHuiCheng: "Partially returned js",
    buFenTuiHuiZhong: "Partially returning js",
    chaoShiWeiQueRen: "Failed to confirm receipt within the specified time js",
    chaoShiWeiQueRen2: "Failed to confirm receipt within the specified time",
    daiQueRenDaoZhang2: "To be confirmed",
    chaoShiCheXiao: "Canceled due to timeout",
    yongHuCheXiao: "Cancel by user",
    buDanShenHeZhong: "Additional order under review",
    renGongJuJueBu: "Reject additional order manually",
    buDanShenHeJu: "Additional order rejected",
    buDanShenHeCheng: "Additional order approved",
    shuZiHuoBi: "Digital currency",
    nu: "Female",
    nan: "Male",
    moRen: "Default",
    youXi: "Games",
    huiYuanDaiChongHui: "Deduction for top-up by members",
    daiChongCaoZuo: "Intermediary top-up operation",
    jianBiTuiHui: "Deduction return",
    shangFenFanLi: "Rebate for top-up",
    vIPDengJi: "VIP level",
    vIPDengJi2: "By VIP level in descending order",
    vIPDengJi3: "VIP level - Upgrade bonus",
    huiFuShenHeZhong: "Restoring review",
    qingChuShenHeZhong: "Clearing review",
    yiQingChu: "Cleared",
    haoYouTuiJian: "Refer friends",
    vIPYueDu2: "VIP monthly gift",
    liuShuiQingLing: "Zero out turnover",
    jiaBiBuJiHong: "Top-up (excluded from bonus)",
    tiaoZhengLiuShui: "Adjust turnover",
    huiFuLiuShui: "Restore turnover",
    qingChuLiuShui: "Clear turnover",
    huoDongHongLiFan: "Event bonus - Rebate event",
    jiaBiDaiLiBu: "Top-up - Agent Department top-up (excluded from bonus)",
    jiaBiCaiWuBu: "Top-up - Finance Department top-up (excluded from bonus)",
    jiaBiHuoDongHong: "Top-up - Event bonus (included in bonus)",
    jiaBiHongBaoJi: "Top-up - Red packet (included in bonus)",
    shangFen: "Top-up",
    meiYueVIP: "Monthly VIP red packet",
    shengJiLiJin: "Upgrade bonus",
    shengRiLiJin: "Birthday bonus",
    weiSuoDing: "Not locked",
    yiSuoDing: "Locked",
    yinHangKaHao: "Bank card No.",
    shangJiDaiLi: "Superior agent",
    zhuCeIP: "Registration IP",
    youXiang: "Email",
    zhuCeSheBeiHao: "Registration device number",
    huiYuanZhangHao: "Member account",
    liXian: "Offline",
    zaiXian: "Available",
    dengLuChengGong: "Logged in",
    dengLuShiBaiBu: "Login failed - department locked",
    dengLuShiBaiBu2: "Login failed - department does not exist",
    dengLuShiBaiGang: "Login failed - job locked",
    dengLuShiBaiGang2: "Login failed - job does not exist",
    dengLuShiBaiZhang: "Login failed - account expired",
    dengLuShiBaiZhang2: "Login failed - account does not exist",
    dengLuShiBaiZhang3: "Login failed - account locked",
    dengLuShiBaiGu: "Login failed- incorrect Google verification code",
    dengLuShiBaiYong: "Login failed- incorrect username or password",
  },
  memberReview: {
    shenHeGeZhi: "Risk review on hold",
    xiuGaiYaoQingJiang: "Modify invitation reward",
    xiuGaiHaoYouLei: "Modify friend type",
  },
  operationManagement: {
    meiCiDengRu: "Every login",
    fuChuang: "Floating window",
    tanChuang: "Pop-up window",
    yiJieShu: "Ended",
  },
  proxyDomain: {
    zhuanShuYuMing: "Exclusive domain name",
    puTongYuMing: "Common domain name",
  },
  report: {
    daiLiZhangHao: "Agent account:",
    huiYuanZhangHao: "Member account",
    yin: "Indonesia",
    yinNiPeiLu: "Indonesian odds",
    ma: "?",
    maLaiXiYaPei: "Malaysian odds",
    xiangGangPeiLu: "Hong Kong odds",
    ouZhouPeiLu: "European odds",
  },
  silentMember: {
    weiTouZhuShiJian: "Time since last bet",
    weiCunKuanShiJian: "Time since last deposit",
    weiDengLuShiJian: "Time since last login",
    jinXianALaBai: "Only integers are allowed.",
  },
  squareConfig: {
    shuBan: "Lose half",
    yingBan: "Win half",
    he: "Draw",
    quanShu: "All lose",
    quanYing: "All win",
    wu: "N/A",
    xiaoJin: "188bet",
    daXiao: "Size",
    rangQiu: "Handicap",
    duYing: "1X2",
    dianZiJingJi: "Esports",
    daXiaoQiu: "Goal over/under",
    lanQiu: "Basketball",
    jiaoQiuDaXiao: "Corner kick over/under",
    zuQiu: "Football",
    shenHeShiJian: "Review time",
    faBuShiJian: "Release time",
    yiZhiDing: "Pinned to top",
    weiZhiDing: "Not pinned to top",
    daiTiJiao: "To be submitted",
  },
  stationLetter: {
    tuPian: "Image",
    hTMLWen: "HTML text",
    yiJinYong: "Disabled",
    yiQiYong: "Enabled",
    zhuanJiaBaoLiaoTui: "Expert tips push",
    fuLiZhongXinTui: "Benefit center push",
    zhuBoTuiSong: "Streamer push",
    saiShiTuiSong: "Match push",
    huoDongTuiSong: "Event push",
    tian: "15–30 days",
    tian2: "7–15 days",
    tian3: "1 day",
    xiaoShi: "Hour",
    xiaoShi2: "3 hours",
    xiaoShi3: "1 hour",
    zhuanJiaBaoLiaoFa: "Expert tips release",
    zhuBoDongTaiFa: "Streamer updates release",
    zhuBoShangXian: "Streamer is online",
    fuLiZhongXin: "Rewards",
    meiYueHongBao: "Monthly red packet",
    vIPJinJi: "VIP upgrade bonus",
    suoYouYongHu: "All users",
    yiCheXiao: "Revoked",
    yiTuiSong: "Pushed",
    daiTuiSong: "To be pushed",
    dingShiTuiSong: "Scheduled push",
    liJiTuiSong: "Push now",
    daiZhuanZhang: "To be transferred",
    chuanGuan: "Parlay",
    danChang: "Single bet",
    zhong: "2 out of 3",
    zhong2: "1 out of 3",
    zhong3: "1 out of 2",
    hei: "Lose",
    hong: "Win",
    zhiDing: "Pin to top",
    tanChuWenBen: "Pop-up text",
    tiaoZhuanYeMian: "Redirection page",
    tiaoZhuanSaiShi: "Redirection match",
    qiTa: "Others",
    daiLiXiaJiHui: "Agent's subordinate members",
    tian4: "days",
    xiaoShi4: "Hour",
    fenZhong: "Minute(s)",
    tuiGuangSuCaiYuan: "Original images of promotion materials",
    zengSongTuiGuangTu: "Gift promotion image",
    zanZhuTuiGuangTu: "Sponsorship promotion image",
    aPPTuiGuang: "App promotion image",
    daiLiAND: "Agent - Android",
    daiLiIOS: "Agent - iOS",
    daiLiHDuan: "Agent - H5",
    daiLiPCDuan: "Agent - PC",
    huiYuanAND: "Member - Android",
    huiYuanIOS: "Member - iOS",
    huiYuanHDuan: "Member - H5",
    huiYuanPCDuan: "Member - PC",
    vIPShengJi: "VIP upgrade progress",
    liJin: "Bonus",
    diGuan: "Level 10",
    diGuan2: "Level 9",
    diGuan3: "Level 8",
    diGuan4: "Level 7",
    diGuan5: "Level 6",
    diGuan6: "Level 5",
    diGuan7: "Level 4",
    diGuan8: "Level 3",
    diGuan9: "Level 2",
    diGuan10: "Level 1",
    yOPLA: "Yoplay slot",
    xINLaoHu: "XIN slot",
    aGINLao: "AGIN slot",
    aGBuYu: "AG Fishing",
    aGDianZi: "Asia Gaming (AG)",
    aGZhenRen: "AG Live Game",
    huLue: "Ignore",
    ziDongJieJin: "Automatically unmute",
    renGongJieJin: "Manually unmute",
    jinYan: "Mute",
    jinYanJieShuShi: "Mute end time",
    jinYanKaiShiShi: "Mute start time",
    jinYanZhong: "Muting",
    juBaoCiShu: "Number of reports <",
    juBaoCiShu2: "Number of reports >",
    waiBuLaQu: "External pull",
    benZhanHuiYuan: "Members of this site",
    shangJiZhuanRuDai: "Transfer from superior (intermediary top-up)",
    xiTongXiaoXiZi: "System message (funds)",
    xiTongXiaoXiSuo: "System message (locked)",
  },
};
