export default {
  components: {
    yunWeiXiTong: "O&M system",
    yongHuXiTong: "User system",
    shuJuXiTong: "Data system",
    fengKongXiTong: "Risk control system",
    yunYingXiTong: "Operation system",
    caiWuXiTong: "Financial system",
    shouHuoDiZhi: "Shipping address",
    shuJuQuanXian: "Data permissions:",
    shuJuKeJian: "Data visible:",
    gangWeiQuanXianShe: "Job permission settings ({val1})",
    gongXiNinCaoZuo: "Congratulations. The operation is successful.",
    fuZhiQuanXian: "Copy permissions",
    gangWeiMa: "Job?",
    queDingJiangXuanZhong: "Copy the selected job permissions to",
    fuZhiChengGong: "Copied.",
    feiBiXuanMoRen: "Optional permissions are unchecked by default. Check them to see all the information.",
    zuiJinDengLu: "Last login",
    chengYuanGuanLi: "Member management",
    pOSTI: "{val1} remarks:",
    pOSTJ: "{val1} remarks:",
    qingShuRuGangBei: "Enter job remarks:",
    beiZhu: "Remark",
    qingShuRuGangWei: "Enter the job name.",
    gangWeiMingChengI: "Job name {val1}",
    qingShuRuBeiZhu: "Enter the remarks.",
    gangWeiMingChengN: "Job name 0&nbsp;",
    qingShuRuBeiZhu2: "Enter remarks:",
    qingShuRuBuMen: "Enter the department name.",
    buMenMingCheng: "Department name",
    bianJiBuMen: "Edit department",
    xinZengBuMenGang: "New department/job",
    gongXiCaoZuoCheng: "Congratulations. The operation is successful.",
    beiZhuNAM: "Remarks: {val1}",
  },
  config: {
    gangWeiQuanXianShe: "Job permission settings ({val1})",
  },
  modal: {
    gangWeiQuanXianShe: "Job permission settings ({val1})",
    gaiYeMianZanWu: "Query plan settings are not available on this page.",
    gaiYeMianZanWu2: "Query plan settings are not available on this page.",
    zhuYi: "Note:",
    renXuanQiYiCha: "Select any one to query",
    biTianChaXunTiao: "Required query criteria",
    yunXuChaXunTiao: "Allowed query criteria",
    lieBiaoShiFouLei: "Whether the list is cumulative or not",
    chaXunShiJianFan: "Query time range",
    yeMianQuanXianShe: "Page permission settings",
  },
};
