export default {
  config: {
    chongZhiFangShi: "Top-up method",
    jinE: "Amount:",
    quKuanFang: "Withdrawal person:",
    cunKuanFang: "Depositor:",
    daoZhangShiJian: "Receipt time",
    chongZhiShiJian: "Top-up time",
    dingDanBianHao: "Order No.",
    dangQianYeXiaoJi: "Current page total",
    dingDanZhuangTai: "Order status",
    qingShuRuDingDan: "Enter an order number",
    qingShuRuHuiYuan: "Enter the member account number.",
  },
  createOrderDialog: {
    chuangJianDingDanLi: "Order creation history",
    shouKuanKaYinHang: "Bank name of receiving card",
    shouKuanKaXingMing: "Receiving card holder name",
    dingDanJinE: "Order amount",
    shangHuHao: "Merchant No.",
    chongZhiTongDao: "Top-up channel",
    dingDanHao: "Order No.:",
    tianJiaTuPian: "Add image",
    chuangJianDingDan: "Create order",
    zuiDuoZhiNengShang: "Up to 3 images can be uploaded.",
    shouKuanYinHang: "Receiving bank",
    chongZhiShangHuHao: "Top-up merchant No.",
    chongZhiShangHu: "Top-up merchant",
    guanLianDanHao: "Associated order No.",
    dingDanHaoDA: "Order No.: {val1}",
    chuangJianDingDanCheng: "Order created.",
    weiHuoQuDaoGuan: "No associated order No. data obtained",
  },
  detailDialog: {
    dingDanXiangQing: "Order details",
    shouKuanRenXingMing: "Payee name:",
    shouKuanKaHao: "Receiving card No.:",
    sanFangShangHuDing: "Third-party merchant order No.",
    shouXuFei: "Service fee:",
    daoZhangJinE: "Received amount",
    yinHangKaHaoQian: "Bank card No./wallet address",
    chongZhiRenXingMing: "Top-up person name",
    shouKuanYinHangQian: "Receiving bank/Wallet protocol",
    chongZhiLeiXing: "Top-up type",
    zhiFuShangHuHao: "Payment merchant No.",
    zhiFuShangHuMing: "Payment merchant name",
    chongZhiDanHao: "Top-up order No.:",
    buDanShenHeBei: "Additional order review remarks",
    buDanShenHeRen: "Additional order reviewer",
    buDanShenHeShi: "Additional order review time",
    buDanFaQiRen: "Additional order initiator",
    buDanShiJian: "Additional order time",
    buDanJinE: "Additional order amount",
    shiJiShouDaoU: "USDT received",
    shiJiHuiLu: "Real exchange rate",
    dingDanHuiLu: "Order exchange rate",
    daiZhiFuUS: "USDT to be paid",
    juHeDingDanXiang: "Aggregated orders details",
    quDaoShangHuHao: "Channel merchant No.",
    xiaYouQuDao: "Downstream channel",
    wuPingZhengJieTu: "No voucher screenshot",
  },
  index: {
    chongZhiJinE: "Top-up amount",
  },
  repairOrderDialog: {
    buDanShenQing: "Additional order request",
    shangHuHouTaiDing: "Merchant backend order status",
    queDingJuJue: "Reject?",
    baoCunChengGong: "Saved",
    tuPianShangChuanCuo: "Image upload error",
  },
};
