export default {
  gameInquiry: {
    xianKaiQiuQiuDui: "Team that kicks off first",
    hongKaDaXiaoPan: "Red card over/under",
    gunQiuHongKaDa: "In-play red card over/under",
    gunQiuHongKaRang: "In-play red card handicap",
    hongKaRangQiuPan: "Red card handicap",
    yueWeiDaXiaoPan: "Offside over/under",
    gunQiuYueWeiDa: "In-play offside over/under",
    gunQiuYueWeiRang: "In-play offside handicap",
    yueWeiRangQiuPan: "Offside handicap",
    zongJinQiuShu: "Total goals",
    jiaoQiuDaXiaoPan: "Corner kick over/under",
    gunQiuJiaoQiuDa: "In-play corner kick over/under",
    gunQiuJiaoQiuRang: "In-play corner kick handicap",
    jiaoQiuRangQiuPan: "Corner kick handicap",
    deKaZongShuDa: "Total number of cards over/under",
    gunQiuDeKaZong: "In-play total number of cards over/under",
    gunQiuDeKaZong2: "In-play total number of cards handicap",
    deKaZongShuRang: "Total number of cards handicap",
    qiuDuiZongJinQiu: "Total goals of teams",
    gunQiuTeBieTou: "Special in-play bets",
    teBieTouZhu: "Special bet",
    panShuBoDan: "Correct score",
    qiuYuanZongJinQiu: "Total goals of players",
    dianQiuDaXiaoPan: "Penalty kick over/under",
    dianQiuRangQiuPan: "Penalty kick handicap",
    guanJunPanKou: "Outright market",
    danShuang: "Odd/even",
    duYingPan: "1X2",
    zuiHouJinQiuQiu: "Last team to score",
    zuiHouJinQiuQiu2: "Last player to score",
    gunQiuZongJinQiu: "In-play total goals",
    gunQiuDianQiuDa: "In-play penalty kick over/under",
    gunQiuDianQiuRang: "In-play penalty kick handicap",
    gunQiuDaXiao: "In-play over/under",
    gunQiuDanShuang: "In-play odd/even",
    gunQiuDuYingPan: "In-play 1X2",
    gunQiuBanQuanChang: "In-play half/full time",
    gunQiuBoDan: "In-play correct score",
    gunQiuRangQiu: "In-play handicap",
    gunQiuDuYing: "In-play 1X2",
    banQuanChang: "Half/full time",
    zuiXianJinQiuQiu: "First team to score",
    shouWeiJinQiuQiu: "First player to score",
    boDan: "Correct score",
    diSanPan: "3rd set",
    diSanJie: "3rd quarter",
    diLiuPan: "6th set",
    diQiPan: "7th set",
    diErPan: "2nd set",
    diErJie: "2nd quarter",
    xiaBanChang: "Second half",
    fen: "Points",
    jiaShiDianQiu: "Overtime & penalty kick",
    shangBanChang: "First half",
    quanChangFenShuTou: "Full-time score betting",
    quanChang: "Full time",
    diSiPan: "4th set",
    diSiJie: "4th quarter",
    diYiPan: "1st set",
    diYiJie: "1st quarter",
    diWuPan: "5th set",
    diSiCiJiaShi: "4th overtime",
    diSanCiJiaShi: "3rd overtime",
    diErCiJiaShi: "2nd overtime",
    diYiCiJiaShi: "1st overtime",
    qianWuJu: "First 5 rounds",
    xiao: "Under",
    huoYiShang: "7 or above",
    huoYiShang2: "3 or above",
    da: "Over",
    qiTa: "Others",
    dan: "Odd",
    wuJinQiu: "No goals",
    zhuDuiJingShengQiu: "Home - 5 or more goal difference",
    zhuDui: "Home",
    zhuZhu: "Home-home",
    zhuHe: "Home-draw",
    zhuKe: "Home-away",
    shuang: "Even",
    heJu: "Draw",
    heZhu: "Draw-home",
    heHe: "Draw-draw",
    heKe: "Draw-away",
    keDui: "Away",
    keDuiJingShengQiu: "Away - 5 or more goal difference",
    qiTaBiFen: "Other scores",
    keZhu: "Away-home",
    keHe: "Away-draw",
    keKe: "Away-away",
    dongJiYunDong: "Winter sports",
    paiQiu: "Volleyball",
    tianJing: "Athletics",
    wangQiu: "Tennis",
    pingPangQiu: "Table tennis",
    youYong: "Swimming",
    teBieXiangMu: "Special matches",
    leiQiu: "Softball",
    siNuoKeTaiQiu: "Snooker/billiard",
    ganLanQiu: "Rugby",
    saiChe: "Racing",
    gengDuoYunDong: "More sports",
    bingQiu: "Ice hockey",
    shouQiu: "Handball",
    tiCao: "Gymnastics",
    gaoErFuQiu: "Golf",
    shiNeiZuQiu: "Indoor soccer",
    jinRongTouZhu: "Financial bet",
    quGunQiu: "Hockey",
    feiBiao: "Darts",
    ziXingChe: "Cycling",
    banQiu: "Cricket",
    quanJiGeDou: "Boxing/martial arts",
    xuanMeiDaSai: "Beauty pageant",
    shaTanPaiQiu: "Beach volleyball",
    shaTanZuQiu: "Beach football",
    bangQiu: "Baseball",
    yuMaoQiu: "Badminton",
    meiShiZuQiu: "American football",
    touZhuNeiRong: "Bet",
    zongPeiLu: "Total odds",
    xiaZhuNeiRong: "Bet content",
    danChangPeiLu: "Single bet odds",
    saiShi: "Matches",
    ziYouXi: "Sub-games",
    xiang: "Item",
    chuanGuan: "Parlay",
    tongBuShiJian: "Sync time",
    xiaZhuIP: "Bet placing IP",
    gongSiYingLi: "Company profit",
    gongSiChouShui: "Company vigorish",
    touZhuJinE: "Stake is less then the minimum value of the betting range.",
    paiCaiJinE: "Payout amount",
    zhuDanZhuangTai: "Betslip status",
    saiShiIDJu: "Match ID/round No.",
    youXiPingTai: "Game platform",
    youXiZhangHuMing: "Game account name",
    touZhuID: "Bet ID",
    touZhuID2: "Bet ID",
    sanFangDingDanHao: "Third-party order No.:",
    zhuDanHao: "Betslip No.",
    quanBuHuiZong: "Total summary",
    qingXuanZeShiFou: "Select whether to delist.",
    tiQianJieSuan: "Settle in advance",
    zhenDuiTiYuZhu: "For sports betslip, enter English.",
    lianSaiMingCheng: "League tournament name",
    dingDanZhuangTai: "Order status",
    qingShuRuZhuDan: "Enter the betslip number",
    qingShuRuZhangHao: "Enter an account name/phone No.",
    wuXiaoDingDanI: "Invalid order: {val1} orders with a bet amount of {val2} CNY.",
    yiQuXiaoZhuDan: "Canceled betslips: {val1} orders with a bet amount of {val2} CNY.",
    weiJieSuanZhuDan: "Unsettled betslips: {val1} orders with a bet amount of {val2} CNY.",
    zhi: "to",
    dETAI: "{val1}, etc. ({val2} items), a total of {val3} CNY",
    dIVLianSai: "<div>League tournament: {val1}</div>\n <div>Both sides:{val2}</div>\n <div>Options: {val3}, {val4} - {val5} - {val6}, </div>\n {val7}</div>",
    wuXiaoDingDanI2: "Invalid order: {val1} orders with a bet amount of {val2} CNY.",
    yiQuXiaoZhuDan2: "Canceled betslips: {val1} orders with a bet amount of {val2} CNY.",
    weiJieSuanZhuDan2: "Unsettled betslips: {val1} orders with a bet amount of {val2} CNY.",
    dETAI2: "{val1}, etc. ({val2} items), a total of {val3} CNY",
    dIVLianSai2: "null",
  },
  rechargeRebateSummary: {
    daiChongFanLiZong: "Total rebates for intermediary top-up",
    cuoWuDaiChongKou: "Deduction for incorrect intermediary top-up",
    huiYuanDaiChongZong: "Total amount of top-up by members",
    shengYuXinYongZong: "Total remaining credit",
    yiShiYongXinYong: "Total credit used",
    xinYongZongE: "Total credit",
    yueFen: "Month",
    jieSuanYueFen: "Settlement month",
    shengYuXinYongE: "Remaining credit limit",
    yiShiYongXinYong2: "Credit limit used",
    xinYongEDu: "Credit limit",
    mingXiShuJuYue: "Month of breakdown data:",
  },
};
