export default {
  accountBlanceStatistics: {
    huiZongYuE: "Total balance",
    jinRiYuEMing: "Balance details today",
    huiZong: "Summary",
    chaKanMingXi: "View details",
    shiJian: "Time",
    shuJuLeiXing: "Data type",
    chaXunShiJian: "Query time",
    suoYouYeHuiZong: "Summary of all pages",
    zhangHuLeiXing: "Account type",
    qingShuZhangHuMing: "Enter an account name.",
  },
  bet_recharge: {
    qingXuanZeTiaoZheng: "Select a level after adjustment.",
    touZhuChongZhiTong: "Betting and top-up statistics",
  },
  common: {
    riQi: "Date:",
    zuoRi: "Yesterday",
    jinRi: "Today",
    gongSiYouXiYing: "Profit-loss summary of company game",
    zhanBi: "Share",
    ziJinLiang: "Fund amount",
    biShu: "Transactions",
    zongJi: "Total:",
    tongDaoLeiBie: "Channel category",
    mingXiShuJu: "Details data",
    gongSiShuYingGong: "Company win/loss: Company win/loss = PvP win + Platform dealer win",
    wanJiaDuiZhanWan: "PvP: PvP profit = Vigorish",
    pingTaiZuoZhuangPing: "Platform dealer: Platform dealer win = Stake - Payout",
    youXiMingCheng: "Game name",
    shaShu: "Kills",
    youXiLeiXing: "Game type",
    shaiXuan: "Filter",
    yi: "Monday",
    mATHR: "{val1}0,000",
    yongHuCengJiZhan: "Share by user level",
    liShiShouCunRen: "Historical first deposit users",
    jinRiShouCunRen: "First deposit users today",
    shi: "Yes",
    shi2: "Sun Dec 31 1899 09:00:00 GMT+0800 (台北標準時間)",
    shi3: "0",
    daKeHu: "Major customers",
    youZhiCeng: "High-end level",
    douDiCeng: "Bottom layer",
    shi4: "Mon Jan 01 1900 08:00:00 GMT+0800 (台北標準時間)",
    shi5: "Mon Jan 01 1900 07:00:00 GMT+0800 (台北標準時間)",
    shi6: "Mon Jan 01 1900 06:00:00 GMT+0800 (台北標準時間)",
    shi7: "Mon Jan 01 1900 05:00:00 GMT+0800 (台北標準時間)",
    shi8: "Mon Jan 01 1900 04:00:00 GMT+0800 (台北標準時間)",
    shi9: "Mon Jan 01 1900 02:00:00 GMT+0800 (台北標準時間)",
    shi10: "Mon Jan 01 1900 01:00:00 GMT+0800 (台北標準時間)",
    shi11: "Mon Jan 01 1900 00:00:00 GMT+0800 (台北標準時間)",
    shi12: "Sun Dec 31 1899 23:00:00 GMT+0800 (台北標準時間)",
    shi13: "Sun Dec 31 1899 22:00:00 GMT+0800 (台北標準時間)",
    shi14: "Sun Dec 31 1899 21:00:00 GMT+0800 (台北標準時間)",
    shi15: "Sun Dec 31 1899 20:00:00 GMT+0800 (台北標準時間)",
    shi16: "Sun Dec 31 1899 19:00:00 GMT+0800 (台北標準時間)",
    shi17: "Sun Dec 31 1899 18:00:00 GMT+0800 (台北標準時間)",
    shi18: "Sun Dec 31 1899 17:00:00 GMT+0800 (台北標準時間)",
    shi19: "Sun Dec 31 1899 16:00:00 GMT+0800 (台北標準時間)",
    shi20: "Sun Dec 31 1899 15:00:00 GMT+0800 (台北標準時間)",
    shi21: "Sun Dec 31 1899 14:00:00 GMT+0800 (台北標準時間)",
    shi22: "Sun Dec 31 1899 13:00:00 GMT+0800 (台北標準時間)",
    shi23: "Sun Dec 31 1899 12:00:00 GMT+0800 (台北標準時間)",
    shi24: "Sun Dec 31 1899 11:00:00 GMT+0800 (台北標準時間)",
    puYu: "Fishing",
    sanFangQiTaChong: "Other 3rd-party top-up method",
    sanFangYinHangKa: "Top-up via 3rd-party bank card",
    ziYouYinHangKa: "Top-up via self-owned bank card",
    zuoRiGongSiShu: "Company win/loss yesterday",
    jinRiGongSiShu: "Company win/loss today",
    youXiFenLei: "Game category",
    zhengTi: "Overall",
    huoYueHuiYuanV: "VIP share in active members",
    huoYueHuiYuan: "Active members",
    huoYueHuiYuanCeng: "Level share in active members",
    feiDaiLi: "Non-agent",
    huoYueHuiYuanFen: "Distribution of active members",
    jinRiLeiJi: "Total today",
    zuoRiLeiJi: "Total yesterday",
    anZhuDanTongJi: "Statistics by betslip",
    anChongZhiTongJi: "Statistics by top-up",
    anDengLuTongJi: "Statistics by login",
    xinZengHuiYuanFen: "Distribution of new members",
    xinZengHuiYuan: "New members",
    zuoRiHongLiJin: "Bonus amount yesterday",
    jinRiHongLiJin: "Bonus amount today",
    hongLiJinE: "Bonus amount",
    zuoRiTouZhuRen: "Bet placers yesterday",
    jinRiTouZhuRen: "Bet placers today",
    touZhuRenShuTong: "Bet placer statistics",
    zhengDianYouXiaoTou: "Hourly valid bets",
    jinRiLeiJiYou: "Total valid bets today",
    zuoRiLeiJiYou: "Total valid bets yesterday",
    youXiaoTouZhuJin: "Valid stake",
    anVIPFen: "Category by VIP",
    zhengDianShouCun: "Hourly first deposit",
    jinRiLeiJiShou: "Total first deposit today",
    zuoRiLeiJiShou: "Total first deposit yesterday",
    shouCunRenShu: "First deposit users",
    vIPDengJi: "VIP level",
    jinRiTiXianJin: "Withdrawal amount today",
    tiXianZongBiShu: "Total withdrawal transactions",
    tiXianZongRenShu: "Total users of withdrawal",
    tiXianZongRenShu2: "Total users of withdrawal/Total withdrawal transactions",
    zhengDianTiXian: "Hourly withdrawal",
    jinRiLeiJiTi: "Total withdrawal today",
    zuoRiLeiJiTi: "Total withdrawal yesterday",
    tiXianZongJinE: "Total withdrawal amount",
    jinRiDaiChongJin: "Intermediary top-up amount today",
    daiChongBiShu: "Intermediary top-up transactions",
    daiChongRenShu: "Intermediary top-up users",
    daiChongRenShuDai: "Intermediary top-up users/transactions",
    zhengDianChongZhi: "Hourly top-up",
    jinRiLeiJiChong: "Total top-up today",
    zuoRiLeiJiChong: "Total top-up yesterday",
    daiChongJinE: "Intermediary top-up amount:",
    zhiFuFangShiChong: "Top-up summary of payment method",
    shangHuChongZhiHui: "Top-up summary of merchant",
    yinHangKaChongZhi: "-- Step 2 for top-up via bank card -->\nimport",
    jinRiChongZhiJin: "Top-up amount today",
    xuNiBiChongZhi: "Cryptocurrency top-up transactions",
    xuNiBiChongZhi2: "Cryptocurrency top-up users",
    xuNiBiChongZhi3: "Cryptocurrency top-up users/Cryptocurrency top-up transactions",
    xuNiBiChongZhi4: "Cryptocurrency top-up amount",
    chongZhiZongBiShu: "Total top-up transactions",
    chongZhiZongRenShu: "Total top-up users",
    chongZhiZongRenShu2: "Total top-up users/Total top-up transactions",
    chongZhiZongJinE: "Total top-up amount",
    anVIPTong: "Statistics by VIP",
    dengLuDuan: "Login terminal",
    anHuoDongFenLei: "Category by activity",
    anVIPFen2: "Category by VIP",
    anYouXiFenLei: "Category by game",
    vIPHongLi: "VIP bonus amount",
    vIPHongLi2: "VIP bonus",
    fanShuiHongLiJin: "Rebate bonus amount",
    fanShuiHongLi: "Rebate bonus",
    qiTaHongLiJin: "Other bonus amount",
    qiTaHongLi: "Other bonuses",
    touZhuRenShu: "Bet placers",
    youXiaoTouZhuJin2: "Valid stake statistics",
    liShiJinRi: "Today in history",
    anVIPTong2: "Statistics by VIP",
    iHao: "No. {val1}",
    qingShuRuSuoShu: "Enter the affiliated agent.",
    suoShuShangJi: "Superior agent",
    yongHuMing: "Username",
    shouCunShiJian: "First deposit time:",
    hongLiZongE: "Total bonus",
    canYuCiShu: "Times participated",
    canYuRenShu: "Participants",
    zuoRiXinZengHui: "New members yesterday",
    xinZengHuiYuan2: "New members",
    jinRiXinZengHui: "New members today",
    zuoRiHuoYueHui: "Active members yesterday",
    huoYueHuiYuanDeng: "Active members (logged in)",
    fanShuiJinE: "Rebate amount",
    canYuRenShu2: "Participants",
    xiaZhuRenShu: "Bet placers:",
    zuoRiXiaZhuRen: "Players who placed bets yesterday",
    xiaZhuJinE: "Bet amount:",
    jinRiXiaZhuRen: "Players who placed bets today",
    zuoRiYouXiaoTou: "Valid bets yesterday",
    shaShu2: "Kills",
    zuoRiYingLi: "Profit yesterday",
    zuoRiShouCunRen: "First deposit users yesterday",
    shouCunRenShu2: "First deposit users",
    jinRiShouCunRen2: "First deposit users today",
    huiYuanShouCunDai: "First deposit by member + Intermediary top-up amount",
    zuoRiShouCunJin: "First deposit amount yesterday",
    tiXianBiShu: "Withdrawal transactions",
    zuoRiTiXianJin: "Withdrawal amount yesterday",
    daiChongBiShu2: "Intermediary top-up transactions",
    daiChongRenShu2: "Intermediary top-up users",
    zuoRiDaiChongJin: "Intermediary top-up amount yesterday",
    chongZhiBiShu: "Top-up transactions",
    chongZhiRenShu: "Top-up users",
    zuoRiChongZhiJin: "Top-up amount yesterday",
    fanShuiShiJian: "Rebate issued at",
    faFangCiShu: "Times issued",
    faFangRenShu: "Recipients",
    youHuiLeiXing: "Offer type",
    daiChong: "Intermediary top-up",
    shouCunLeiXing: "First deposit type",
    zhuCeShiJian: "Registration time:",
    huiYuanMing: "Member name",
    tiXianBiShu2: "Withdrawal transactions",
    chongZhiBiShu2: "Top-up transactions",
    zhangHaoLeiXing: "Account type",
    zongTouZhuE: "Total stake",
  },
};
