export default {
  config: {
    qingShuRuZhengShu: "Enter an integer.",
    buKeShuRuE: "Emoji cannot be entered.",
    weiZiFuZiMu: "A combination of 8 to 20 letters and numbers",
    weiShuZiZiMu: "A combination of 3 to 16 numbers and letters",
    qingShuRuWeiDe: "Enter a password of 8 to 20 characters.",
    zhangHaoBiXuYi: "Account must start with a letter and contain 6 to 16 characters consisting of English letters and numbers.",
    biXuZaiZhiJian: "It must be between 0 and 100.",
    banBenHaoGeShi: "Incorrect format of version number.",
    miMaChangDuZai: "The password must be a combination of 8 to 20 characters consisting of at least 2 types of characters among numbers, letters, and special characters.",
    yongHuMingBiXu: "Username must be a combination of 6 to 16 characters consisting of letters and numbers and must start with a letter.",
    qingShuRuYongDou: "Enter integers separated with commas (,).",
    yongHuMingZhiNeng: "Username must be a combination of Chinese characters, numbers, letters, and underscores.",
    yongHuMingChangDu: "Username must contain 6 to 16 characters.",
    zuiDuoZhiChiWei: "It can be up to 128 characters in length (up to 64 Chinese characters).",
    qingShuRuYiH: "Enter a correct URL starting with "http" or "https".",
    weiDeShuZiZi: "A combination of 5 to 12 numbers and letters",
    weiShuZiZiMu2: "A combination of 5 to 20 numbers, letters, or underscores",
    weiShuZiZiMu3: "A combination of 5 to 20 numbers and letters",
    ziMuKaiTouZhi: "It must start with a letter and only contain numbers and letters.",
    qingShuRuWeiDe2: "Enter a password of 6 to 20 characters.",
    qingShuRuZhengQue: "Enter a correct username or phone No.",
    yinHangKaBiXu: "Bank card must be a number of 15 to 19 digits.",
    ninShuRuDeZhi: "Incorrect Alipay account.",
    feiKaiTouDeWei: "A number of 5 to 15 digits not starting with "0"",
    weiDeShuZiZi2: "6 to 20 numbers, letters, or underscores",
    tuPianGeShiBu: "Incorrect image format.",
    buNengShuRuTe: "Unable to enter a special character.",
    baoHanLiangWeiXiao: "It contains 2 decimal places.",
    qingShuRuZhengQue2: "Enter a correct amount.",
    qingShuRuZhengQue3: "Enter the correct email address.",
    qingShuRuZhongWen: "Enter Chinese text.",
    qingShuRuDaYu: "Enter a positive integer greater than 0.",
    qingShuRuZhengZheng: "Enter a positive integer.",
    qingShuRuZhengShu2: "Enter a positive number of less than or equal to 2 decimal places.",
    qingShuRuShuZi: "Enter a number.",
  },
  index: {
    jianYanXiangWeiKong: "Verification item is empty.",
    zuiDuoZhiChiR: "It can be up to {val1} characters in length (up to {val2} Chinese characters).",
  },
  utils: {
    henYiHanZuiDuo: "What a pity. You can enter up to {val1} {val2}.",
    ninShuRuDeT: "Your entered {val1} is duplicate, with {val2} duplicate at \r\n{val3}\r\n{val4}).",
    henYiHanZuiDuo2: "What a pity.', 'You can enter up to {val1} {val2}.'',",
    ninShuRuDeT2: "null",
  },
};
