export default {
  model: {
    buCunZaiDeZhang: "Non-existing account: {val1}",
    yiJingCunZaiFen: "Existing assignment account: {val1}",
  },
  payment: {
    tuiHui: "Back",
    fengKongShenHeShi: "Risk control review time",
    qianBaoDiZhi: "Wallet address",
    yinHangMingCheng: "Bank name:",
    chuKuanShangHu: "Payout merchant:",
    chuKuanFangShi: "Payout method:",
    yongHuCengJi: "User level:",
    huiYuanXingMing: "Member name",
    zhangHuXinXi: "Account info",
    tiXianDingDanJin: "Withdrawal order amount",
    dangQianYeHuiZong: "Summary of the current page",
    chuKuanJiLu: "Payout history",
    xuanZeChuKuanShang: "Select a payout merchant/top-up member.",
    qingShuRuDanHao: "Enter the order No.",
    tiXianShiJianDuan: "Withdrawal period",
    queDingQiangZhiShi: "Confirm to force fail it?",
    qiangZhiShiBai: "Force fail",
    qiangZhiChengGong: "Forced successfully",
    juJueYuanYin: "Reason for rejection",
    uSDTShu: "USDT amount",
    canKaoHuiLu: "Reference exchange rate",
    qingShuRuChuKuan: "Enter the payout account information.",
    chuKuanZhangHuXin: "Payout account info",
    qingShuRuChuKuan2: "Enter a payout account.",
    chuKuanZhangHao: "Payout account",
    chuKuanJinE: "Payout amount",
    kaiHuXingDiZhi: "Bank address/wallet address",
    yinHangKaHaoXie: "Bank card number/protocol type",
    yinHangMingChengU: "Bank name/USDT withdrawal",
    queRenChuKuan: "Confirm payout",
    buZhiChiYuE: "Balance query not supported",
    qingShuRuChuKuan3: "Enter the card holder's name for the payout.",
    chuKuanKaYinHang: "Payout bank",
    chuKuanKaXingMing: "Payout card holder's name",
    yuE: "Balance",
    chuKuanZhiFuShang: "Payout merchant",
    shuRuHuiYuanXing: "Enter a member name.",
  },
  record: {
    tiXianLeiXing: "Withdrawal type",
    chuKuanShiJian: "Payout time",
    tiXianShiJian: "Withdrawal time:",
    quKuanJinE: "Withdrawal amount",
  },
  utils: {
    baiFenBi: "Percentage",
    yuanBi: "CNY/transaction",
    qingShuRuChongZhi: "Enter the top-up amount.",
    qingXuanZeTiJiao: "Select the submission time.",
  },
};
