export default {
  component: {
    di: "No.",
    tiaoJiLu: "entries",
    gong: "Total",
    shouQi: "Hide",
    zhanKai: "Expand",
  },
  globalHeader: {
    chaKanGengDuo: "View more",
    zanWuShuJu: "No data",
    qingKongLe: "Cleared",
    qingKong: "Clear",
    niYiWanChengSuo: "You have completed all to-dos.",
    daiBan: "To-do",
    ninYiDuWanSuo: "You have read all messages.",
    xiaoXi: "Message",
    niYiChaKanSuo: "You have read all notifications.",
    tongZhi: "Notification",
    shiYongWenDang: "User manual",
    souSuoTiShiSan: "Search prompt 3",
    souSuoTiShiEr: "Search prompt 2",
    souSuoTiShiYi: "Search prompt 1",
    zhanNeiSouSuo: "In-site search",
  },
  menu: {
    yunYingGuanLi: "Operation management",
    shuJuTongJi: "Data statistics",
    baoBiaoZhongXin: "Report center",
    chenMoHuiYuan: "Silent member",
    touZhuJiLu: "Bet history",
    daiLiYuMingGuan: "Affiliate domain name management",
    daiLiLieBiao: "Affiliate list",
    ziJinTiaoZheng: "Fund adjustment",
    zhanNeiXin: "Internal message",
    cunQuJiLu: "Withdrawal and deposit records",
  },
  pwa: {
    shuaXin: "Refresh",
    qingDianJiShuaXin: "Click "Refresh" or manually refresh the page.",
    youXinNeiRong: "New content available",
    dangQianChuYuLi: "Offline",
  },
  settingDrawer: {
    peiZhiLanZhiZai: "null",
    kaoBeiChengGongQing: "Copied. Open src/defaultSettings.js to replace the default configuration.",
    kaoBeiSheZhi: "Copy settings",
    seRuoMoShi: "Color weakness mode",
    qiTaSheZhi: "Other settings",
    guDingHEA: "Configurable with fixed header",
    xiaHuaShiYinCang: "Hide header when a slide-down gesture is detected",
    ceBianCaiDanBu: "Configurable with side menu layout",
    guDingCeBianCai: "Fixed side menu",
    guDingHEA2: "Fixed header",
    dingBuCaiDanBu: "Top menu layout",
    ceBianCaiDanBu2: "Side menu layout",
    daoHangMoShi: "Navigation mode",
    jiangZi: "Dark purple",
    jiKeLan: "Geek blue",
    fuXiaoLanMoRen: "Dawn blue (default)",
    jiGuangLu: "Aurora green",
    mingQing: "Bright green",
    riMu: "Sunset",
    huoShan: "Volcano",
    boMu: "Twilight",
    zhuTiSe: "Theme color",
    liuShi: "Dynamic",
    dingKuan: "Fixed width",
    neiRongQuYuKuan: "Content area width",
    liangSeCaiDanFeng: "Light menu",
    anSeCaiDanFeng: "Dark menu",
    zhengTiFengGeShe: "Style settings",
  },
  settings: {
    guan: "OFF",
    kai: "ON",
    daiBanRenWuJiang: "To-dos are sent via internal messages.",
    daiBanRenWu: "To-do task",
    xiTongXiaoXiJiang: "System messages are sent via internal messages.",
    xiTongXiaoXi: "【System message】",
    qiTaYongHuDe: "Messages from other users are sent via internal messages.",
    zhangHuMiMa: "Password",
    bangDing: "Bind",
    dangQianWeiBangDing: "No DingTalk account bound.",
    bangDingDingDing: "Bind DingTalk account",
    dangQianWeiBangDing2: "No Alipay account bound.",
    bangDingZhiFuBao: "Bind Alipay account",
    dangQianWeiBangDing3: "No Taobao account bound.",
    bangDingTaoBao: "Bind Taobao account",
    sheZhi: "Settings",
    xiuGai: "Modify",
    weiBangDingMF: "No MFA device bound. Secondary confirmation is supported after an MFA device is bound.",
    mFASheBei: "MFA device",
    yiBangDingYouXiang: "Email bound",
    beiYongYouXiang: "Secondary email",
    weiSheZhiMiBao: "Security question not set. Security questions can help improve account security.",
    miBaoWenTi: "Security question",
    yiBangDingShouJi: "Phone No. bound.",
    miBaoShouJi: "Security phone No.",
    dangQianMiMaQiang: "Password strength",
    ruo: "Weak",
    zhong: "2 out of 3",
    qiang: "Strong",
    gengXinJiBenXin: "Update basic info",
    qingShuRuNinDe: "Enter your real name.",
    lianXiDianHua: "Phone No.",
    qingShuRuNinDe2: "Enter your street address.",
    jieDaoDiZhi: "Address",
    qingShuRuNinDe3: "Enter your province and city.",
    suoZaiShengShi: "Province and city",
    qingShuRuNinDe4: "Enter your country or region.",
    guoJiaDiQu: "Country/region",
    geRenJianJie: "Profile",
    qingShuRuGeRen: "Enter your profile.",
    qingShuRuNinDe5: "Enter your nickname.",
    niCheng: "Nickname",
    qingShuRuNinDe6: "Enter your email address.",
    gengHuanTouXiang: "Change profile photo",
    touXiang: "Profile photo",
    xinXiaoXiTongZhi: "New message notification",
    zhangHaoBangDing: "Account binding",
    anQuanSheZhi: "Security settings",
    jiBenSheZhi: "Basic settings",
  },
};
