export default {
  components: {
    gangWeiLeiBie: '岗位类别',
    miMa: '密码',
    tiJiao: '提交',
    bianJiZhangHao: '编辑账号',
    xinJianZhangHao: '新建账号',
    qingShuRuDaiLi: '请输入代理，多个账户名请用","隔开',
    shuRuDaiLi: '输入代理',
    keJianDaiLi: '可見代理',
    youXiaoShiJian: '有效时间',
    zhangHaoYouXiaoQi: '账号有效期',
    qingXuanZeGangWei: '请选择岗位类别',
    qingShuRuMiMa: '请输入密码',
    qingShuRuZhangHao: '请输入账号名',
    gongXiNinBianJi: '恭喜您，编辑账号成功',
    gongXiNinXinZeng: '恭喜您，新增账号成功',
    shenFenMa: '身份码',
    shenFenYanZhengMa: '身份验证码',
    zhongZhiShenFenYan: '重置身份验证码',
    qingShuRuBeiZhu: '请输入备注',
    beiZhuROW: '备注：{val1}',
  },
  config: {
    tianJiaBeiZhu: '添加备注',
    xiuGaiRen: '修改人',
    gangWeiMingCheng: '岗位名称',
    buMenMingCheng: '部门名称',
    qingShuRuZhangHao: '请输入账号',
  },
  index: {
    yunWeiGuanLiXi: '运维管理系统',
  },
};
