export default {
  createSystemModal: {
    qingXuanZeXiTong: '请选择系统图标',
    xiTongTuBiao: '系统图标',
    qingXuanZeXiTong2: '请选择系统描述',
    xiTongMiaoShu: '系统描述',
    qingShuRuXiTong: '请输入系统名称',
    xiTongMingCheng: '系统名称',
    chuangJianYeWuXi: '创建业务系统/管理业务系统',
    qingGouXuanXiTong: '请勾选系统权限!',
    xinHuaiDaXiangFa: '心怀大想法，享受小乐趣',
    chengGongJiuShiRi: '成功就是日复一日点滴努力的积累',
    tianShiBuRuDi: '天时不如地利，地利不如人和',
    yunWeiDeShiJie: '运维的世界像古老的时钟，滴滴答答',
    shengMingJiuXiangYi: '生命就像一盒巧克力，结果往往出人意料',
    shuJuJiuXiangYi: '数据就像一本魔法书，所有技能都可以在这里愉快获取',
    guiHuaDeMuDi: '规划的目的是为了更快更有效地达成目标',
    dangFengXianLaiLin: '当风险来临时，用微笑去面对，用智慧去解决',
  },
  index: {
    guanLiXiTongQuan: '管理系统权限',
    zuiHouXiuGaiShi: '最后修改时间',
    chuangJianShiJian: '创建时间',
    qingQiuZuiXinCai: '请求最新菜单',
    gongXiNiQingQiu: '恭喜你，请求最新菜单成功！',
  },
};
