export default {
  utils: {
    beiShu: '倍数：',
    haoMa: '号码：',
    jieGuo: '结果：',
    weiZhi: '位置：',
    wanFa: '玩法：',
    weiZhi2: '位置',
    touZhuWeiZhi: '投注位置',
    haoMa2: '号码',
    touZhuHaoMa: '投注号码',
    wanFaPLA: '玩法：{val1}，位置：{val2}，号码：{val3}，',
    touZhu: '投注:',
    touZhuXiang: '投注项：',
    zhuang: '庄',
    zhuangXian: '庄闲',
    gang: '港',
    xiangGang: '香港',
    ou: '欧',
    ouZhou: '欧洲',
    quanXuan: '全选',
  },
};
