export default {
  config: {
    shenHeZhuangTai: '审核状态',
    shenQingBeiZhu: '申请备注',
    tiaoZhengJinE: '调整金额',
    shenHeRen: '审核人',
    shenHe: '审核',
    erShenZhuangTai: '二审状态',
    yiShenZhuangTai: '一审状态',
    xuQiuLiuShuiJin: '需求流水金额',
    keTiEDu: '可提额度',
    tiaoZhengZiLeiXing: '调整子类型',
    tiaoZhengLeiXing: '调整类型',
  },
  index: {
    quanBuLieBiao: '全部列表',
    daiShenHeLieBiao: '待审核列表',
  },
  pageFundsAdjustApplyModal: {
    qingShuRuTiaoZheng: '请输入调整原因',
    tiaoZhengYuanYin: '调整原因',
    qingShuRuSanFang: '请输入三方商户订单号',
    qingShuRuGuanLian: '请输入关联订单号',
    qingShuRuXuQiu: '请输入需求流水金额',
    qingShuRuTiXian: '请输入提现额度，不可大于调整金额',
    keTiXianEDu: '可提现额度',
    danBiADJ: '单笔≤{val1} 元',
    qingShuRuChongZhi: '请输入充值金额，无充值填入0',
    tiXianLiuShui: '提现流水',
    shiJiFaFangJin: '实际发放金额',
    jiangLiJinE: '奖励金额',
    daiLiHuoDongXuan: '代理活动选择',
    qingShuRuYongHu: '请输入用户名',
    ziJinTiaoZhengShen: '资金调整申请',
    qingXuanZeDaiLi: '请选择代理活动',
    zhangHaoSUC: '账号 {val1} 资金调整申请成功',
    zhangHaoFAI: '账号 {val1} 不支持{val2}',
    zhangHaoINV: '账号 {val1} 不存在',
  },
  pageFundsAdjustExamineModal: {
    jinBanNianJiaBi: '近半年加币记录',
    qingXuanZeShenHe: '请选择审核结果',
    shenHeJieGuo: '审核结果',
    erShenBeiZhu: '二审备注',
    yiShenBeiZhu: '一审备注',
    shenQingYuanYou: '申请原由',
    erCiShenHe: '二次审核',
    yiCiShenHe: '一次审核',
  },
  pageFundsAdjustment: {
    qingXuanZeCaoZuo: '请选择操作数据',
  },
};
