export default {
  activity: {
    fuZhiQuanXianCheng: '复制权限成功',
    xiuGaiZhuangTaiCheng: '修改状态成功',
    tianJiaGangWeiCheng: '添加岗位成功',
  },
  authority_job: {
    kaiQi: '开启',
    caiWuJingLi: '财务经理',
    huYunJuHeZhi: '虎云聚合支付',
    guanBi: '关闭',
  },
  fund_adjustment: {
    caoZuoChengGong: '操作成功',
    tiaoZhengShenQingCheng: '调整申请成功',
  },
  fund_history: {
    baoCunXiuGaiCheng: '保存修改成功',
    teShuQuDao: '特殊渠道',
  },
  fund_information: {
    shanChuChengGong: '删除成功',
    zhongGuoYinHang: '中国银行',
  },
  fund_recharge: {
    daHuCeng: '大户层',
  },
  fund_warn: {
    sanFangZhangHuJin: '三方账户金额 < 10000000.00；',
    sanFangZhangHuJin2: '三方账户金额 > 10000000.00；',
  },
  notices: {
    jinXingZhong: '进行中',
    guanLinTiJiaoYu:
      '冠霖提交于 2017-01-06，需在 2017-01-07 前完成代码变更任务',
    aBCDBan: 'ABCD 版本发布',
    yiHaoShiTian: '已耗时 8 天',
    zhiPaiZhuErYu: '指派竹尔于 2017-01-09 前完成更新并发布',
    xinXiAnQuanKao: '信息安全考试',
    maShangDaoQi: '马上到期',
    diSanFangJinJi: '第三方紧急代码变更',
    weiKaiShi: '未开始',
    renWuXuYaoZai: '任务需要在 2017-01-12 20:00 前启动',
    renWuMingCheng: '任务名称',
    zheZhongMuBanYong: '这种模板用于提醒谁与你发生了互动，左侧放『谁』的头像',
    biaoTi: '标题',
    zhuPianYouHuiFu: '朱偏右 回复了你',
    miaoShuXinXiMiao: '描述信息描述信息描述信息',
    quLiLiPingLun: '曲丽丽 评论了你',
    neiRongBuYaoChao: '内容不要超过两行字，超出时自动截断',
    zuoCeTuBiaoYong: '左侧图标用于区分不同的类型',
    zheZhongMuBanKe: '这种模板可以区分多种通知类型',
    niTuiJianDeQu: '你推荐的 曲妮妮 已通过第三轮面试',
    niShouDaoLeFen: '你收到了 14 份新周报',
  },
  user: {
    xiHuQuGongZhuan: '西湖区工专路 77 号',
    hangZhouShi: '杭州市',
    zheJiangSheng: '浙江省',
    haiNaBaiChuan: '海纳百川',
    chuanMeiZi: '川妹子',
    daChangTui: '大长腿',
    la: '辣~',
    zhuanZhuSheJi: '专注设计',
    henYouXiangFaDe: '很有想法的',
    maYiJinFuMou: '蚂蚁金服－某某某事业群－某某平台部－某某技术部－UED',
    jiaoHuZhuanJia: '交互专家',
    haiNaBaiChuanYou: '海纳百川，有容乃大',
  },
};
