export default {
  addNoticeLetter: {
    yuLanAPP: '预览APP效果',
    yuLanPCXiao: '预览PC效果',
    miaoShu: '描述',
    qingShuRuBiaoTi: '请输入标题',
    xuanZe: '选择',
    duoGeYongHuMing:
      '多个用户名请用逗号(,)或换行隔开，一次最多发送{val1}个账号',
    faSongZhangHao: '发送账号',
    qingXuanZeHuiYuan: '请选择会员层级',
    huiYuanCengJi: '会员层级',
    faSongShiJian: '发送时间',
    faSongZhanNeiXin: '发送站内信',
    geNBSP: '个,&nbsp;&nbsp;',
    nBSPN: ',&nbsp;&nbsp; 失败',
    chengGongFaSong: '成功发送',
    dianJiZhangHaoZhang: '（点击账号账号名可以复制）',
    gongXiNiXiuGai: '恭喜你，修改成功！',
  },
  addUserModal: {
    tiao: ')条:',
    huiYuanLieBiao: '会员列表(',
    qingShuRuSuoShu: '请输入所属代理',
    qingXuanZeVI: '请选择VIP等级',
    vIPDengJi: 'VIP等级',
    xuanZeHuiYuan: '选择会员',
    tianJia: '添加',
    qingChaXunHuiYuan: '请查询会员账号',
  },
  checkAccountList: {
    xiangQing: '详情',
  },
  checkNoticeLetter: {
    huiFuNeiRong: '回复内容',
    huiFuShiJian: '回复时间',
    leiBie: '类别',
    zhengWen: '正文',
    faSongHuiYuan: '发送会员',
  },
  checkReplyLetter: {
    huiFu: '回复',
    jieShouShiJian: '接收时间',
    miaoShuTuPian: '描述图片',
  },
  mobilePreview: {
    wuYuLanNeiRong: '无预览内容展示',
    qinAiDeYongHu: '亲爱的用户您好！',
  },
  replyLetterComponent: {
    buKeChaoGuoGe: '不可超过150个字符',
    dingShiFaSong: '定时发送',
    liJiFaSong: '立即发送',
    faSongZhi: '发送至',
    baoCunShiBaiD: '保存失败.{val1}',
    qingXuanZeRiQi: '请选择日期！',
    qingShuRuNeiRong: '请输入内容！',
  },
  typeSettingModal: {
    changDuZaiDaoGe: '长度在 1 到 30 个字符',
    qingShuRuLeiBie: '请输入类别描述',
    leiBieMiaoShu: '类别描述',
    qingShuRuLeiBie2: '请输入类别名',
    leiBieMing: '类别名',
  },
};
