export default {
  components: {
    yunWeiXiTong: '运维系统',
    yongHuXiTong: '用户系统',
    shuJuXiTong: '数据系统',
    fengKongXiTong: '风控系统',
    yunYingXiTong: '运营系统',
    caiWuXiTong: '财务系统',
    shouHuoDiZhi: '收货地址',
    shuJuQuanXian: '数据权限：',
    shuJuKeJian: '数据可见：',
    gangWeiQuanXianShe: '岗位权限设置 ({val1})',
    gongXiNinCaoZuo: '恭喜您，操作成功！',
    fuZhiQuanXian: '复制权限',
    gangWeiMa: '岗位吗?',
    queDingJiangXuanZhong: '确定将选中岗位权限复制到',
    fuZhiChengGong: '复制成功~',
    feiBiXuanMoRen: '非必选，默认全不勾选，勾选后可查看全部信息',
    zuiJinDengLu: '最近登录',
    chengYuanGuanLi: '成员管理',
    pOSTI: '{val1}备注：',
    pOSTJ: '{val1}备注：',
    qingShuRuGangBei: '请输入岗备注：!',
    beiZhu: '备注：',
    qingShuRuGangWei: '请输入岗位名称!',
    gangWeiMingChengI: '岗位名称{val1}',
    qingShuRuBeiZhu: '请输入备注!',
    gangWeiMingChengN: '岗位名称0&nbsp;',
    qingShuRuBeiZhu2: '请输入备注：!',
    qingShuRuBuMen: '请输入部门名称!',
    buMenMingCheng: '部门名称：',
    bianJiBuMen: '编辑部门',
    xinZengBuMenGang: '新增部门/岗位',
    gongXiCaoZuoCheng: '恭喜， 操作成功~',
    beiZhuNAM: '备注：{val1}',
  },
  config: {
    gangWeiQuanXianShe: '岗位权限设置',
  },
  modal: {
    gangWeiQuanXianShe: '岗位权限设置 ({val1})',
    gaiYeMianZanWu: '该页面暂无查询方案',
    gaiYeMianZanWu2: '该页面暂无查询方案的设置',
    zhuYi: '注意',
    renXuanQiYiCha: '任选其一查询',
    biTianChaXunTiao: '必填查询条件',
    yunXuChaXunTiao: '允许查询条件',
    lieBiaoShiFouLei: '列表是否累计',
    chaXunShiJianFan: '查询时间范围',
    yeMianQuanXianShe: '页面权限设置（{val1}/ {val2}——{val3}）',
  },
};
