export default {
  config: {
    chongZhiFangShi: '充值方式',
    jinE: '金额',
    quKuanFang: '取款方:',
    cunKuanFang: '存款方:',
    daoZhangShiJian: '到帳時間',
    chongZhiShiJian: '充值時間',
    dingDanBianHao: '订单编号',
    dangQianYeXiaoJi: '当前页小计',
    dingDanZhuangTai: '訂單状态',
    qingShuRuDingDan: '请输入订单编号',
    qingShuRuHuiYuan: '请输入会员账号',
  },
  createOrderDialog: {
    chuangJianDingDanLi: '创建订单历史记录',
    shouKuanKaYinHang: '收款卡银行',
    shouKuanKaXingMing: '收款卡姓名',
    dingDanJinE: '订单金额',
    shangHuHao: '商户号',
    chongZhiTongDao: '充值通道',
    dingDanHao: '订单号',
    tianJiaTuPian: '添加图片',
    chuangJianDingDan: '创建订单',
    zuiDuoZhiNengShang: '最多只能上传3张图片',
    shouKuanYinHang: '收款银行',
    chongZhiShangHuHao: '充值商户号',
    chongZhiShangHu: '充值商户',
    guanLianDanHao: '关联单号',
    dingDanHaoDA: '订单号：{val1}',
    chuangJianDingDanCheng: '创建订单成功',
    weiHuoQuDaoGuan: '未获取到关联单号数据',
  },
  detailDialog: {
    dingDanXiangQing: '订单详情',
    shouKuanRenXingMing: '收款人姓名',
    shouKuanKaHao: '收款卡号',
    sanFangShangHuDing: '三方商户订单号',
    shouXuFei: '手续费',
    daoZhangJinE: '到账金额',
    yinHangKaHaoQian: '银行卡号/钱包地址',
    chongZhiRenXingMing: '充值人姓名',
    shouKuanYinHangQian: '收款银行/钱包协议',
    chongZhiLeiXing: '充值类型',
    zhiFuShangHuHao: '支付商户号',
    zhiFuShangHuMing: '支付商户名',
    chongZhiDanHao: '充值单号',
    buDanShenHeBei: '补单审核备注',
    buDanShenHeRen: '补单审核人',
    buDanShenHeShi: '补单审核时间',
    buDanFaQiRen: '补单发起人',
    buDanShiJian: '补单时间',
    buDanJinE: '补单金额',
    shiJiShouDaoU: '实际收到USDT',
    shiJiHuiLu: '实际汇率',
    dingDanHuiLu: '订单汇率',
    daiZhiFuUS: '待支付USDT',
    juHeDingDanXiang: '聚合订单详情',
    quDaoShangHuHao: '渠道商户号',
    xiaYouQuDao: '下游渠道',
    wuPingZhengJieTu: '无凭证截图',
  },
  index: {
    chongZhiJinE: '充值金额：',
  },
  repairOrderDialog: {
    buDanShenQing: '补单申请',
    shangHuHouTaiDing: '商户后台订单状态',
    queDingJuJue: '确定拒绝',
    baoCunChengGong: '保存成功！',
    tuPianShangChuanCuo: '图片上传错误',
  },
};
