export default {
  accountBlanceStatistics: {
    huiZongYuE: '汇总余额',
    jinRiYuEMing: '今日余额明细',
    huiZong: '汇总',
    chaKanMingXi: '查看明细',
    shiJian: '时间',
    shuJuLeiXing: '数据类型',
    chaXunShiJian: '查询时间',
    suoYouYeHuiZong: '所有页汇总',
    zhangHuLeiXing: '账户类型',
    qingShuZhangHuMing: '请输账户名',
  },
  bet_recharge: {
    qingXuanZeTiaoZheng: '请选择调整方式',
    touZhuChongZhiTong: '投注充值统计',
  },
  common: {
    riQi: '日期',
    zuoRi: '昨日',
    jinRi: '今日',
    gongSiYouXiYing: '公司游戏盈亏汇总{}',
    zhanBi: '占比',
    ziJinLiang: '资金量',
    biShu: '笔数',
    zongJi: '总计',
    tongDaoLeiBie: '通道类别',
    mingXiShuJu: '明细数据',
    gongSiShuYingGong: '公司输赢：公司输赢 = 玩家对战盈利 + 平台坐庄盈利',
    wanJiaDuiZhanWan: '玩家对战：玩家对战盈利 = 抽水',
    pingTaiZuoZhuangPing: '平台坐庄：平台坐庄盈利 = 投注额 - 派彩',
    youXiMingCheng: '游戏名称',
    shaShu: '杀数',
    youXiLeiXing: '游戏类型',
    shaiXuan: '筛选：',
    yi: '亿',
    mATHR: '{val1}万',
    yongHuCengJiZhan: '用户层级占比',
    liShiShouCunRen: '历史首存人数',
    jinRiShouCunRen: '今日首存人数',
    shi: '02时',
    shi2: '01时',
    shi3: '00时',
    daKeHu: '大客户',
    youZhiCeng: '优质层',
    douDiCeng: '兜底层',
    shi4: '24时',
    shi5: '23时',
    shi6: '22时',
    shi7: '21时',
    shi8: '20时',
    shi9: '18时',
    shi10: '17时',
    shi11: '16时',
    shi12: '15时',
    shi13: '14时',
    shi14: '13时',
    shi15: '12时',
    shi16: '11时',
    shi17: '10时',
    shi18: '09时',
    shi19: '08时',
    shi20: '07时',
    shi21: '06时',
    shi22: '05时',
    shi23: '04时',
    shi24: '03时',
    puYu: '扑鱼',
    sanFangQiTaChong: '三方其他充值方式',
    sanFangYinHangKa: '三方银行卡充值',
    ziYouYinHangKa: '自有银行卡充值',
    zuoRiGongSiShu: '昨日公司输赢',
    jinRiGongSiShu: '今日公司输赢',
    youXiFenLei: '游戏分类',
    zhengTi: '整体',
    huoYueHuiYuanV: '活跃会员VIP占比',
    huoYueHuiYuan: '活跃会员',
    huoYueHuiYuanCeng: '活跃会员层级占比',
    feiDaiLi: '非代理',
    huoYueHuiYuanFen: '活跃会员分布',
    jinRiLeiJi: '今日累计',
    zuoRiLeiJi: '昨日累计',
    anZhuDanTongJi: '按注单统计',
    anChongZhiTongJi: '按充值统计',
    anDengLuTongJi: '按登录统计',
    xinZengHuiYuanFen: '新增会员分布',
    xinZengHuiYuan: '新增会员',
    zuoRiHongLiJin: '昨日红利金额',
    jinRiHongLiJin: '今日红利金额',
    hongLiJinE: '红利金额',
    zuoRiTouZhuRen: '昨日投注人数',
    jinRiTouZhuRen: '今日投注人数',
    touZhuRenShuTong: '投注人数统计',
    zhengDianYouXiaoTou: '整点有效投注',
    jinRiLeiJiYou: '今日累计有效投注',
    zuoRiLeiJiYou: '昨日累计有效投注',
    youXiaoTouZhuJin: '有效投注金额',
    anVIPFen: '按vip分类',
    zhengDianShouCun: '整点首存',
    jinRiLeiJiShou: '今日累计首存',
    zuoRiLeiJiShou: '昨日累计首存',
    shouCunRenShu: '首存人数',
    vIPDengJi: 'VIP等级占比',
    jinRiTiXianJin: '今日提现金额',
    tiXianZongBiShu: '提现总笔数',
    tiXianZongRenShu: '提现总人数',
    tiXianZongRenShu2: '提现总人数/提现总笔数',
    zhengDianTiXian: '整点提现',
    jinRiLeiJiTi: '今日累计提现',
    zuoRiLeiJiTi: '昨日累计提现',
    tiXianZongJinE: '提现总金额',
    jinRiDaiChongJin: '今日代充金额',
    daiChongBiShu: '代充笔数',
    daiChongRenShu: '代充人数',
    daiChongRenShuDai: '代充人数/代充笔数',
    zhengDianChongZhi: '整点充值',
    jinRiLeiJiChong: '今日累计充值',
    zuoRiLeiJiChong: '昨日累计充值',
    daiChongJinE: '代充金额',
    zhiFuFangShiChong: '支付方式充值汇总',
    shangHuChongZhiHui: '商户充值汇总 ',
    yinHangKaChongZhi: '银行卡充值占比',
    jinRiChongZhiJin: '今日充值金额',
    xuNiBiChongZhi: '虚拟币充值笔数',
    xuNiBiChongZhi2: '虚拟币充值人数',
    xuNiBiChongZhi3: '虚拟币充值人数/虚拟币充值笔数',
    xuNiBiChongZhi4: '虚拟币充值金额',
    chongZhiZongBiShu: '充值总笔数',
    chongZhiZongRenShu: '充值总人数',
    chongZhiZongRenShu2: '充值总人数/充值总笔数',
    chongZhiZongJinE: '充值总金额',
    anVIPTong: '按VIP统计',
    dengLuDuan: '登录端',
    anHuoDongFenLei: '按活动分类',
    anVIPFen2: '按VIP分类',
    anYouXiFenLei: '按游戏分类',
    vIPHongLi: 'VIP红利金额',
    vIPHongLi2: 'VIP红利',
    fanShuiHongLiJin: '返水红利金额',
    fanShuiHongLi: '返水红利',
    qiTaHongLiJin: '其他红利金额',
    qiTaHongLi: '其他红利',
    touZhuRenShu: '投注人数',
    youXiaoTouZhuJin2: '有效投注金额统计',
    liShiJinRi: '历史今日',
    anVIPTong2: '按vip统计',
    iHao: '{val1}号',
    qingShuRuSuoShu: '请输入所属上级',
    suoShuShangJi: '所属上级',
    yongHuMing: '用户名',
    shouCunShiJian: '首存时间',
    hongLiZongE: '红利总额',
    canYuCiShu: '参与次数',
    canYuRenShu: '参与人数',
    zuoRiXinZengHui: '昨日新增会员数',
    xinZengHuiYuan2: '新增会员 ',
    jinRiXinZengHui: '今日新增会员数 ',
    zuoRiHuoYueHui: '昨日活跃会员',
    huoYueHuiYuanDeng: '活跃会员(登录)',
    fanShuiJinE: '返水金额 ',
    canYuRenShu2: '参与人数 ',
    xiaZhuRenShu: '下注人数 ',
    zuoRiXiaZhuRen: '昨日下注人数 ',
    xiaZhuJinE: '下注金额 ',
    jinRiXiaZhuRen: '今日下注人数 ',
    zuoRiYouXiaoTou: '昨日有效投注',
    shaShu2: '杀数 ',
    zuoRiYingLi: '昨日盈利 ',
    zuoRiShouCunRen: '昨日首存人数',
    shouCunRenShu2: '首存人数 ',
    jinRiShouCunRen2: '今日首存人数 ',
    huiYuanShouCunDai: '会员首存 + 代充金额',
    zuoRiShouCunJin: '昨日首存金额',
    tiXianBiShu: '提现笔数 ',
    zuoRiTiXianJin: '昨日提现金额',
    daiChongBiShu2: '代充笔数 ',
    daiChongRenShu2: '代充人数 ',
    zuoRiDaiChongJin: '昨日代充金额',
    chongZhiBiShu: '充值笔数 ',
    chongZhiRenShu: '充值人数 ',
    zuoRiChongZhiJin: '昨日充值金额',
    fanShuiShiJian: '返水时间',
    faFangCiShu: '发放次数',
    faFangRenShu: '发放人数',
    youHuiLeiXing: '优惠类型',
    daiChong: '代充',
    shouCunLeiXing: '首存类型',
    zhuCeShiJian: '注册时间',
    huiYuanMing: '会员名',
    tiXianBiShu2: '提现笔数',
    chongZhiBiShu2: '充值笔数',
    zhangHaoLeiXing: '账号类型',
    zongTouZhuE: '总投注额',
  },
};
