export default {
  model: {
    buCunZaiDeZhang: '不存在的账号：{val1}',
    yiJingCunZaiFen: '已经存在分单账号：{val1}',
  },
  payment: {
    tuiHui: '退回',
    fengKongShenHeShi: '风控审核时间',
    qianBaoDiZhi: '钱包地址',
    yinHangMingCheng: '银行名称',
    chuKuanShangHu: '出款商户',
    chuKuanFangShi: '出款方式',
    yongHuCengJi: '用户层级',
    huiYuanXingMing: '会员姓名',
    zhangHuXinXi: '账户信息',
    tiXianDingDanJin: '提现订单金额',
    dangQianYeHuiZong: '当前页汇总',
    chuKuanJiLu: '出款记录',
    xuanZeChuKuanShang: '选择出款商户',
    qingShuRuDanHao: '请输入单号',
    tiXianShiJianDuan: '提现时间段',
    queDingQiangZhiShi: '确定强制失败吗？',
    qiangZhiShiBai: '强制失败',
    qiangZhiChengGong: '强制成功',
    juJueYuanYin: '拒绝原因',
    uSDTShu: 'USDT数量',
    canKaoHuiLu: '参考汇率',
    qingShuRuChuKuan: '请输入出款账户信息',
    chuKuanZhangHuXin: '出款账户信息',
    qingShuRuChuKuan2: '请输入出款账号',
    chuKuanZhangHao: '出款账号',
    chuKuanJinE: '出款金额',
    kaiHuXingDiZhi: '开户行地址/钱包地址',
    yinHangKaHaoXie: '银行卡号/协议类型',
    yinHangMingChengU: '银行名称/USDT提现',
    queRenChuKuan: '确认出款',
    buZhiChiYuE: '不支持余额查询',
    qingShuRuChuKuan3: '请输入出款卡姓名',
    chuKuanKaYinHang: '出款卡银行',
    chuKuanKaXingMing: '出款卡姓名',
    yuE: '余额',
    chuKuanZhiFuShang: '出款支付商户',
    shuRuHuiYuanXing: '输入会员姓名',
  },
  record: {
    tiXianLeiXing: '提现类型',
    chuKuanShiJian: '出款時間',
    tiXianShiJian: '提現時間',
    quKuanJinE: '取款金额：',
  },
  utils: {
    baiFenBi: '百分比',
    yuanBi: '元/笔',
    qingShuRuChongZhi: '请输入充值单号',
    qingXuanZeTiJiao: '请选择提交时间',
  },
};
