export default {
  component: {
    di: '  第  ',
    tiaoJiLu: '  条记录  ',
    gong: '  共  ',
    shouQi: '收起',
    zhanKai: '展开',
  },
  globalHeader: {
    chaKanGengDuo: '查看更多',
    zanWuShuJu: '暂无数据',
    qingKongLe: '清空了',
    qingKong: '清空',
    niYiWanChengSuo: '你已完成所有待办',
    daiBan: '待办',
    ninYiDuWanSuo: '您已读完所有消息',
    xiaoXi: '消息',
    niYiChaKanSuo: '你已查看所有通知',
    tongZhi: '通知',
    shiYongWenDang: '使用文档',
    souSuoTiShiSan: '搜索提示三',
    souSuoTiShiEr: '搜索提示二',
    souSuoTiShiYi: '搜索提示一',
    zhanNeiSouSuo: '站内搜索',
  },
  menu: {
    yunYingGuanLi: '运营管理',
    shuJuTongJi: '数据统计',
    baoBiaoZhongXin: '报表中心',
    chenMoHuiYuan: '沉默会员',
    touZhuJiLu: '投注纪录',
    daiLiYuMingGuan: '代理域名管理',
    daiLiLieBiao: '代理列表',
    ziJinTiaoZheng: '资金调整',
    zhanNeiXin: '站內信',
    cunQuJiLu: '存取纪录',
  },
  pwa: {
    shuaXin: '刷新',
    qingDianJiShuaXin: '请点击“刷新”按钮或者手动刷新页面',
    youXinNeiRong: '有新内容',
    dangQianChuYuLi: '当前处于离线状态',
  },
  settingDrawer: {
    peiZhiLanZhiZai:
      '配置栏只在开发环境用于预览，生产环境不会展现，请拷贝后手动修改配置文件',
    kaoBeiChengGongQing: '拷贝成功，请到 src/defaultSettings.js 中替换默认配置',
    kaoBeiSheZhi: '拷贝设置',
    seRuoMoShi: '色弱模式',
    qiTaSheZhi: '其他设置',
    guDingHEA: '固定 Header 时可配置',
    xiaHuaShiYinCang: '下滑时隐藏 Header',
    ceBianCaiDanBu: '侧边菜单布局时可配置',
    guDingCeBianCai: '固定侧边菜单',
    guDingHEA2: '固定 Header',
    dingBuCaiDanBu: '顶部菜单布局',
    ceBianCaiDanBu2: '侧边菜单布局',
    daoHangMoShi: '导航模式',
    jiangZi: '酱紫',
    jiKeLan: '极客蓝',
    fuXiaoLanMoRen: '拂晓蓝（默认）',
    jiGuangLu: '极光绿',
    mingQing: '明青',
    riMu: '日暮',
    huoShan: '火山',
    boMu: '薄暮',
    zhuTiSe: '主题色',
    liuShi: '流式',
    dingKuan: '定宽',
    neiRongQuYuKuan: '内容区域宽度',
    liangSeCaiDanFeng: '亮色菜单风格',
    anSeCaiDanFeng: '暗色菜单风格',
    zhengTiFengGeShe: '整体风格设置',
  },
  settings: {
    guan: '关',
    kai: '开',
    daiBanRenWuJiang: '待办任务将以站内信的形式通知',
    daiBanRenWu: '待办任务',
    xiTongXiaoXiJiang: '系统消息将以站内信的形式通知',
    xiTongXiaoXi: '系统消息',
    qiTaYongHuDe: '其他用户的消息将以站内信的形式通知',
    zhangHuMiMa: '账户密码',
    bangDing: '绑定',
    dangQianWeiBangDing: '当前未绑定钉钉账号',
    bangDingDingDing: '绑定钉钉',
    dangQianWeiBangDing2: '当前未绑定支付宝账号',
    bangDingZhiFuBao: '绑定支付宝',
    dangQianWeiBangDing3: '当前未绑定淘宝账号',
    bangDingTaoBao: '绑定淘宝',
    sheZhi: '设置',
    xiuGai: '修改',
    weiBangDingMF: '未绑定 MFA 设备，绑定后，可以进行二次确认',
    mFASheBei: 'MFA 设备',
    yiBangDingYouXiang: '已绑定邮箱',
    beiYongYouXiang: '备用邮箱',
    weiSheZhiMiBao: '未设置密保问题，密保问题可有效保护账户安全',
    miBaoWenTi: '密保问题',
    yiBangDingShouJi: '已绑定手机',
    miBaoShouJi: '密保手机',
    dangQianMiMaQiang: '当前密码强度',
    ruo: '弱',
    zhong: '中',
    qiang: '强',
    gengXinJiBenXin: '更新基本信息',
    qingShuRuNinDe: '请输入您的联系电话!',
    lianXiDianHua: '联系电话',
    qingShuRuNinDe2: '请输入您的街道地址!',
    jieDaoDiZhi: '街道地址',
    qingShuRuNinDe3: '请输入您的所在省市!',
    suoZaiShengShi: '所在省市',
    qingShuRuNinDe4: '请输入您的国家或地区!',
    guoJiaDiQu: '国家/地区',
    geRenJianJie: '个人简介',
    qingShuRuGeRen: '请输入个人简介!',
    qingShuRuNinDe5: '请输入您的昵称!',
    niCheng: '昵称',
    qingShuRuNinDe6: '请输入您的邮箱!',
    gengHuanTouXiang: '更换头像',
    touXiang: '头像',
    xinXiaoXiTongZhi: '新消息通知',
    zhangHaoBangDing: '账号绑定',
    anQuanSheZhi: '安全设置',
    jiBenSheZhi: '基本设置',
  },
};
